= Аннотация

Модуль _{ad}_ добавляет в систему {dv} функцию согласования документов.

Модуль предназначен для настройки и управления процессом согласования документов предприятия.

_{ad}_ включает набор инструментов, при помощи которых можно реализовать согласование документов по заранее настроенным маршрутам любой степени сложности, в том числе смешанным (последовательно-параллельным), с использованием механизмов рецензирования и консолидации.

Поставляемое решение не содержит заранее настроенных и готовых к использованию сценариев согласования. Предполагается, что разработка пользовательских сценариев будет выполняться Заказчиком самостоятельно с использованием данного модуля.

== Как организована документация

.Документация модуля содержит следующие разделы:
. xref:module-structure.adoc[Структура модуля] -- перечислены составные части модуля.
. xref:admin:install.adoc[Установка и настройка] -- содержит инструкцию по установке модуля.
. xref:admin:update.adoc[Установка новой версии модуля] -- содержит инструкцию по установке новой версиимодуля.
. Функции администратора -- содержит описание настроек модуля, выполняемых администратором {dv}.
. xref:admin:approval-settings.adoc[Настройка согласований] -- содержит инструкцию по созданию и настройке согласований.
. xref:admin:messages.adoc[Сообщения администратору] -- содержит описание некоторых ошибок, выдаваемых при работе модуля.
. Возможности модуля, уровень подготовки пользователей: приведены <<capabilities,общие сведения>> о модуле, <<user-lvl,требования>> к подготовке пользователей.
. Работа с Конструктором согласований -- приведена инструкция по согласованию документов.

[#capabilities]
== Назначение, функции и основные возможности модуля

{dv} 5. _{ad}_ является _базовым модулем_ системы {dv}, предназначенным для настройки и управления процессом согласования документов организации.

.Модуль обеспечивает выполнение следующих функциональных задач:
* Автоматизация этапов согласования:
** Инициирование -- подготовка документа и создание согласования.
** Согласование (с возможностью рецензирования версий):
*** Параллельное.
*** Последовательное.
** Консолидация:
*** Вынесение решения _Консолидатора_ по замечаниям согласующих -- типы решений в зависимости от настроек в карточке _Этап согласования_. Например, _на подписание_, _на новый цикл согласования_ и другие.
*** Возможность сравнения версий согласуемых файлов и создания консолидированной версии.
*** Отмена согласования.
* Поэтапный принцип создания маршрута согласования, позволяющий комбинировать все возможные типы согласования для любых согласующих лиц.
* Настраиваемый порядок прохождения процесса по этапам, возможность использовать один этап в разных маршрутах согласования.
* Один и тот же маршрут согласования может быть использован в различных видах документов. В то же время можно отправлять один вид документа по разным маршрутам согласования (через механизмы создания карточки согласования.
* Гибкая настройка условий запуска процессов: для каждого этапа согласования есть возможность указать условия его запуска -- предшествующие этапы, которые должны быть завершены с определённым результатом.
* Согласующие лица могут быть заданы/вычислены различными способами:
** Ручной выбор определённого сотрудника.
** Члены заданной группы.
** Обладатели заданной роли.
** Через поисковые слова. Например, "Руководитель инициатора", "Все руководители инициатора", "Инициатор", "Регистратор".
** Из полей карточки согласуемого документа.
** Из результата работы БП.
* Возможность вывода листа согласования в требуемой форме с возможностью печати на любом этапе согласования.
* Индивидуальные настройки заданий для каждого этапа: набор кнопок/операций (набор принимаемых решений), информационное наполнение заданий:
** Варианты настройки длительности заданий, отправляемых участникам процесса:
*** Установка длительности заданий согласующим лицам.
*** Установка длительности определённого этапа.
*** Установка длительности задания/этапа для последующих циклов.
** Применение бизнес-календарей в процессе определения сроков исполнения задания:
*** Специального бизнес-календаря согласования.
*** Личного бизнес-календаря сотрудника.
*** Бизнес календаря группы, отдела и так далее вверх по лестнице иерархии.
* Отслеживание стадий согласования в реальном времени (история и листы согласования), которые участник согласования может просматривать из карточки _Задание_. Лист согласования формируется на основании данных из карточки _Согласование_.
* Использование электронных подписей с выбранной меткой при принятии решения (в зависимости от настроек.

Модуль включает набор инструментов, при помощи которых можно реализовать согласование документов по заранее настроенным маршрутам любой степени сложности, в том числе смешанным (последовательно-параллельным), с использованием механизмов рецензирования и консолидации.

Поставляемое решение не содержит заранее настроенных и готовых к использованию сценариев согласования. Предполагается, что разработка пользовательских сценариев будет выполняться Заказчиком самостоятельно с использованием данного модуля.

[#user-lvl]
== Уровень подготовки пользователя

Для эксплуатации модуля _{ad}_ определены две пользовательские роли: администратор {dv} и конечный пользователь. На этапе внедрения системы {dv} в организации появляется дополнительные роли: инженер и программист {dv}.

Администратор {dv} устанавливает серверную часть модуля, выявляет неполадки в работе бизнес-процессов согласования.

Пользователь отправляет документы на согласование и участвует в согласовании документов.

Инженер {dv} настраивает шаблоны, этапы и маршруты согласования.

Все пользователи модуля должны обладать базовыми навыками работы на персональном компьютере, в {wincl}е (модуль "{dv} 5. {wincl}").

Пользователям необходимо ознакомиться с руководством пользователя модуля {dv} 5. {dm}.

Администратор {dv} должен обладать навыками настройки модуля {pl}, формирования сертификатов ЭЦП в ОС Windows, использования криптопровайдера "КриптоПро"; а также ознакомиться с руководством по администрированию модуля {bo}.

Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}.

Программист должен иметь опыт разработки на языке C# или Visual Basic .NET, а также ознакомиться с документом _{dv} 5.5. Руководство программиста_.
