= Аннотация

Модуль "Конструктор согласований" добавляет в систему "Docsvision 5.5" (далее – "Docsvision") функцию согласования документов.

Модуль предназначен для настройки и управления процессом согласования документов предприятия.

Модуль включает набор инструментов, при помощи которых можно реализовать согласование документов по заранее настроенным маршрутам любой степени сложности, в том числе смешанным (последовательно-параллельным), с использованием механизмов рецензирования и консолидации.

Поставляемое решение не содержит заранее настроенных и готовых к использованию сценариев согласования. Предполагается, что разработка пользовательских сценариев будет выполняться Заказчиком самостоятельно с использованием данного модуля.

== Назначение и функции модуля

"Docsvision 5. Конструктор согласований" является _базовым модулем_ системы "Docsvision 5.5", предназначенным для настройки и управления процессом согласования документов организации.

Модуль обеспечивает выполнение следующих функциональных задач:

* Автоматизация этапов согласования:
** инициирование (подготовка документа и создание согласования);
** согласование (с возможностью рецензирования версий):
*** параллельное;
*** последовательное;
** консолидация:
*** вынесение решения *Консолидатора* по замечаниям согласующих (типы решений – в зависимости от настроек в карточке _Этап согласования_. Например, _на подписание_, _на новый цикл согласования_ и т.п.);
*** возможность сравнения версий согласуемых файлов и создания консолидированной версии;
*** отмена согласования.
* Поэтапный принцип создания маршрута согласования, позволяющий комбинировать все возможные типы согласования для любых согласующих лиц.
* Настраиваемый порядок прохождения процесса по этапам, возможность использования одного этапа в разных маршрутах согласования.
* Один и тот же маршрут согласования может быть использован в различных видах документов, в то же время возможна отправка одного вида документа по разным маршрутам согласования (через механизмы создания карточки согласования).
* Гибкая настройка условий запуска процессов: для каждого этапа согласования есть возможность указать условия его запуска - предшествующие этапы, которые должны быть завершены с определенным результатом.
* Согласующие лица могут быть заданы/вычислены различными способами:
** определенный сотрудник;
** члены заданной группы;
** обладатели заданной роли;
** через поисковые слова ("Руководитель инициатора", "Все руководители инициатора", "Инициатор", "Регистратор");
** из полей карточки согласуемого документа;
** из результата работы БП.
* Возможность вывода листа согласования в требуемой форме с возможностью печати на любом этапе согласования.
* Индивидуальные настройки заданий для каждого этапа: набор кнопок/операций (набор принимаемых решений), информационное наполнение заданий:
** варианты настройки длительности заданий, отправляемых участникам процесса:
*** установка длительности заданий согласующим лицам;
*** установка длительности определенного этапа;
*** установка длительности задания/этапа для последующих циклов;
** Применение бизнес-календарей в процессе определения сроков исполнения задания:
*** специального бизнес-календаря согласования;
*** личного бизнес-календаря сотрудника;
*** бизнес календаря группы, отдела и так далее вверх по лестнице иерархии.
* Отслеживание стадий согласования в реальном времени (история и листы согласования), которые участник согласования может просматривать из карточки _Задание_. Лист согласования формируется на основании данных из карточки _Согласование_.
* Использование электронных подписей с выбранной меткой при принятии решения (в зависимости от настроек).

Модуль включает набор инструментов, при помощи которых можно реализовать согласование документов по заранее настроенным маршрутам любой степени сложности, в том числе смешанным (последовательно-параллельным), с использованием механизмов рецензирования и консолидации.

Поставляемое решение не содержит заранее настроенных и готовых к использованию сценариев согласования. Предполагается, что разработка пользовательских сценариев будет выполняться Заказчиком самостоятельно с использованием данного модуля.

== Как организована документация

.Документация модуля содержит следующие разделы:
. xref:module-structure.adoc[Структура Модуля] (перечислены составные части Модуля).
. xref:admin:install.adoc[Установка и настройка] (содержит инструкцию по установке Модуля).
. xref:admin:UpdateVersion.adoc[Установка новой версии модуля] (содержит инструкцию по установке новой версии Модуля).
. Функции администратора (содержит описание настроек Модуля, выполняемых администратором Docsvision).
. xref:admin:approval-settings.adoc[Настройка согласований] (содержит инструкцию по созданию и настройке согласований).
. xref:admin:Messages.adoc[Сообщения администратору] (содержит описание некоторых ошибок, выдаваемых при работе модуля).
. Возможности модуля, уровень подготовки пользователей (xref:capabilities.adoc[приведены] общие сведения о Модуле, xref:user-level.adoc[требования] к подготовке пользователей).
. Работа с Конструктором согласований (приведена инструкция по согласованию документов).

== Назначение документации

Настоящий раздел документации является руководством пользователя модуля "Docsvision 5. Конструктор согласований" (далее – "Модуль"), который дополняет приложение "Docsvision 5. Управление документами" функциями расширенного согласования.

В раздел приведена инструкция по работе с согласованиями в Windows-клиенте. Базовые принципы работы с заданиями и документами рассмотрены в руководстве пользователя приложения "Docsvision 5. Управление документами"

Раздел предназначен для пользователей системы Docsvision.
