= Бизнес-процессы

.Модуль _{ad}_ добавляет в систему {dv} следующие бизнес-процессы:
. _КС Стартовый процесс_ -- запускается при отправке документа на согласование. Получает ссылки на карточки маршрута/документа/согласования. Считывает настройки из маршрута и атрибуты документа. Осуществляет первичное наполнение карточки _Согласование_. Запускает БП _КС Основной процесс_.
. _КС Основной процесс_ -- работает с этапами, составляющими маршрут. Проверяет условия их старта и запускает соответствующий подпроцесс, который выбирается исходя из типа согласования. Создает ветки в дереве версий файлов. Осуществляет мониторинг завершения этапов.
. _КС Подпроцесс Последовательное согласование_ -- работает с составом согласующих на данном этапе, обрабатывает их решения. Вносит результаты в карточку _Согласование_. Меняет состояния документа. Выполняет последовательную рассылку заданий участникам.
. _КС Подпроцесс Параллельное согласование_ -- работает с составом согласующих на данном этапе. Обрабатывает их решения. Вносит результаты в карточку _Согласование_, меняет состояния документа. Выполняет параллельную рассылку заданий участникам.
. _КС Подпроцесс работы с заданиями_ -- запускается из подпроцессов, соответствующих типу согласования. Формирует задания, наполняет их данными из настроек карточки _Этап согласования_. Обрабатывает результаты, решения, комментарии, файлы и версии. Заполняет карточку _Согласование_.
. _КС Процесс отзыва_ -- обрабатывает принудительную отмену/завершение согласования. Завершает оставшиеся процессы согласований.
. _КС запись информации в Ход согласования при делегировании_.
. _КС запись информации в Ход согласования при отмене делегирования_.
. _КС Процесс запуска после приостановки_.
. _КС Процесс приостановки_.

В бизнес-процессах модуля _{ad}_ используется функция "Задание 5", особенностью которой является создание шаблона карточки Задания с настройками варианта завершения. Копия данного шаблона будет создаваться при запуске БП с функцией "Задание 5". Не рекомендуется удалять данные шаблоны карточек Заданий и их оперативные копии, создаваемые при запуске БП, -- это может привести к ошибке в работе БП.
