= Бизнес-процессы

Модуль "{ad}" добавляет в систему {dv} бизнес-процессы, перечисленные далее.

. "КС Стартовый процесс" -- запускается при отправке документа на согласование; получает ссылки на карточки маршрута/документа/согласования; считывает настройки из маршрута и атрибуты документа; осуществляет первичное наполнение карточки _Согласование_; запускает БП "КС Основной процесс".
. "КС Основной процесс" -- работает с этапами, составляющими маршрут; проверяет условия их старта и запускает соответствующий подпроцесс (выбирается исходя из типа согласования); создает ветки в дереве версий файлов; осуществляет мониторинг завершения этапов.
. "КС Подпроцесс Последовательное согласование" -- работает с составом согласующих на данном этапе, обрабатывает их решения; вносит результаты в карточку _Согласование_; меняет состояния документа; выполняет последовательную рассылку заданий участникам.
. "КС Подпроцесс Параллельное согласование" -- работает с составом согласующих на данном этапе; обрабатывает их решения; вносит результаты в карточку _Согласование_, меняет состояния документа; выполняет параллельную рассылку заданий участникам.
. "КС Подпроцесс работы с заданиями" -- запускается из подпроцессов, соответствующих типу согласования; формирует задания, наполняет их данными (из настроек карточки _Этап согласования_); обрабатывает результаты (решения, комментарии, файлы и версии); заполняет карточку _Согласование_.
. "КС Процесс отзыва" -- обрабатывает принудительную отмену/завершение согласования; завершает оставшиеся процессы согласований.
. "КС запись информации в Ход согласования при делегировании".
. "КС запись информации в Ход согласования при отмене делегирования".
. "КС Процесс запуска после приостановки".
. "КС Процесс приостановки".

В бизнес-процессах модуля "{ad}" используется функция Задание 5, особенностью которой является создание шаблона карточки Задания с настройками варианта завершения. Копия данного шаблона будет создаваться при запуске БП с функцией Задание 5. Не рекомендуется удалять данные шаблоны карточек Заданий и их оперативные копии, создаваемые при запуске БП, -- это может привести к ошибке в работе БП.
