= Виды карточек

[WARNING]
====
include::admin:partial$excerpts.adoc[tags=manual-delete]
====

.Модуль "{ad}" добавляет в _Справочник видов карточек_ следующие виды карточек:
. _Согласование КС_ -- вид карточек, предназначенных для инициирования и выполнения согласований, настроенных в модуле.
+
Связан с карточкой _Маршрут согласования_, хранит в себе ход согласования, историю, файлы и версии, добавленные участниками согласования, также содержит элементы управления согласованием.
+
. _Задание КС_ с подвидами (_На согласование_, _На подписание_, _На консолидацию_) -- вид карточек, отправляемых участникам согласования.
+
Карточки предоставляют пользователю возможность работы с основными файлами: просмотр, создание версий, комментирование, просмотр дополнительных файлов. В ходе всего процесса работы с заданием участник согласования может ввести комментарий или приложить файл комментария.
+
.. _Согласование с контрагентом_ -- предназначен для совершения операций с отдельным заданием по согласованию договорного документа с контрагентом; задание этого вида Создаётся системой автоматически.
.. _Консолидация договора_ -- предназначен для совершения операций с отдельным заданием по консолидации договорного документа в процессе его исполнения. Задание этого вида Создаётся системой автоматически.
.. _Усовершенствованное согласование_ -- меняет поведение элементов управления в карточках согласования и заданиях согласования.
+
Чтобы включить усовершенствованное согласование, необходимо установить соответствующий флаг при создании нового маршрута. Подробнее работа с усовершенствованным согласованием описана xref:admin:route-advanced.adoc[в соответствующем разделе].
+
include::admin:partial$excerpts.adoc[tags=crmodes]
