= Структура модуля

Модуль _{ad}_ состоит из двух частей: Серверная и Клиентская.

.Серверная часть устанавливается на компьютер с сервером {dv} и включает:
. Загружаемые в систему {dv} данные:
* xref:card-kinds.adoc[Типы и виды карточек].
* xref:user-roles.adoc[Роли]
* xref:edit-operations.adoc[Операции редактирования].
* xref:business-processes.adoc[Бизнес-процессы].
* Настройки состояний карточек -- добавляет в _Конструктор состояний_ набор состояний для видов _Согласование КС_, _Задание КС_ с подвидами.
* Разметки карточек -- добавляет в _Конструктор разметок_ разметки для карточек _Этап согласования_, _Маршрут согласования_, _Согласование КС_ и _Задание КС_.
* Группу сотрудников _{dv-ad-admins-dir}_.
* Преднастроенные маршруты согласования.
* Скрипты карточек.
+
[WARNING]
====
При установке модуля будут заново загружены скрипты базового типа карточки Согласование. Все изменения, выполненные для данного типа, будут утеряны. Чтобы вернуть пользовательские настройки для типа, их следует выполнить заново.

Возврат изменений не может быть выполнен путем полного замещения кода, так как скрипты базового типа изменены относительно платформенных скриптов.
====
+
. Хранимые процедуры для БД.
. Библиотеки DLL с компонентами карточек модуля, объектной моделью карточек модуля, _функциями_ БП для обеспечения работы бизнес-процессов модуля.
. Пакет установки клиентской части модуля _{ad}_.

.Клиентская часть устанавливается на компьютеры пользователей {dv} и включает:
. Библиотеки DLL с элементами пользовательского интерфейса карточек модуля.
