= Структура Модуля

Модуль "{ad}" состоит из двух частей:

. Серверная часть (для установки на компьютер с сервером {dv}), которая включает:
[loweralpha]
.. Загружаемые в систему {dv} данные: xref:card-kinds.adoc[типы и виды карточек], xref:user-roles.adoc[роли], xref:edit-operations.adoc[операции редактирования], xref:business-processes.adoc[бизнес-процессы], настройки состояний карточек (добавляет в _Конструктор состояний_ набор состояний для видов _Согласование КС_, _Задание КС_ с подвидами), разметки карточек (добавляет в _Конструктор разметок_ разметки для карточек _Этап согласования_, _Маршрут согласования_, _Согласование КС_ и _Задание КС_), группу сотрудников "Администраторы КС", преднастроенные маршруты согласования, скрипты карточек.
+
[IMPORTANT]
====
При установке Модуля будут заново загружены скрипты базового типа карточки Согласование, при этом все изменения, выполненные для данного типа, будут утеряны. Чтобы вернуть пользовательские настройки для типа, их следует выполнить заново. Возврат изменений не может быть выполнен путем полного замещения кода, так как скрипты базового типа изменены относительно платформенных скриптов.
====
.. Хранимые процедуры для БД.
.. Библиотеки DLL с компонентами карточек Модуля, объектной моделью карточек Модуля, _функциями_ БП для обеспечения работы бизнес-процессов Модуля.
.. Пакет установки клиентской части модуля "{ad}".
. Клиентская часть (для установки на компьютеры пользователей {dv}), которая включает:
[loweralpha]
.. Библиотеки DLL с элементами пользовательского интерфейса карточек Модуля.
