= Требования для установки модуля

== Необходимое техническое обеспечение

Специальные требования к аппаратному обеспечению клиентского и серверного компьютера не предъявляются.

Для корректной работы данной версии модуля "{ad}" требуется установить *серверную* и *клиентскую* части следующих модулей:

.Модули {dv}:
. Модуль {pl} {pl-req} и выше.
. Модуль {bo} {bo-req} и выше.
. Приложение {dm} {ud-req} и выше.
. Модуль wf {wf-req} и выше.
. Приложение Делопроизводство 4.5 {dp-req} и выше.
. Модуль {wincl} {win-req} и выше.

== Лицензия

Для работы с модулем _{ad}_ лицензия на систему {dv} должна содержать дополнительную опцию: _{dv} Approval Designer_.

При отсутствии лицензии в модуле теряется возможность создания расширенных согласований. При попытке создать новые карточки _Этап согласования_ и _Маршрут согласования_ будет выдано сообщение об ошибке: `Лицензия не позволяет работать с конструктором согласований`. При этом, если лицензия отсутствует, возможность работы с ранее созданными маршрутами и этапами согласований сохраняется. Конечные пользователи смогут отправлять задания на согласования по настроенным маршрутам.
