= Требования для установки модуля

== Необходимое техническое обеспечение

Специальные требования к аппаратному обеспечению клиентского и серверного компьютера не предъявляются.

== Требования серверной части модуля

.Модули {dv}:
. Серверная часть модуля {pl} {pl-v} и выше.
. Серверная часть модуля {bo} {bo-v} и выше.
. Серверная часть приложения {ud} {dm-v} и выше.
. Серверная часть модуля 5. Управление процессами {wf-v} и выше.
. Серверная часть приложения Делопроизводство 4.5 {to-v} и выше.
. Серверная часть модуля {wincl} {win-v} и выше.

== Требования клиентской части модуля

.Модули {dv}:
. Клиентская часть модуля {pl} {pl-v} и выше.
. Клиентская часть модуля {bo} {bo-v} и выше.
. Клиентская часть приложения {ud} {dm-v} и выше.
. Клиентская часть модуля Управление процессами {wf-v} и выше.
. Клиентская часть приложения Делопроизводство 4.5 {to-v} и выше.
. Клиентская часть модуля {wincl} {win-v} и выше.

== Лицензия

Для работы с модулем _{ad}_ лицензия на систему {dv} должна содержать дополнительную опцию: _{dv} Approval Designer_.

При отсутствии лицензии в модуле теряется возможность создания расширенных согласований. При попытке создать новые карточки _Этап согласования_ и _Маршрут согласования_ будет выдано сообщение об ошибке: `Лицензия не позволяет работать с конструктором согласований`. При этом, если лицензия отсутствует, возможность работы с ранее созданными маршрутами и этапами согласований сохраняется. Конечные пользователи смогут отправлять задания на согласования по настроенным маршрутам.
