= Требования для установки модуля

[#hard]
== Необходимое техническое обеспечение

Специальные требования к аппаратному обеспечению клиентского и серверного компьютера не предъявляются.

[#dv]
== Требования к системе {dv}

Для корректной работы данной версии модуля _{ad}_ требуется установить *серверные*
// и *клиентскую*
части следующих модулей:

.Модули {dv}:
. Модуль {pl} {pl-req} и выше.
. Модуль {bo} {bo-req} и выше.
. Приложение {dm} {dm-req} и выше.
. Модуль {wf} {wf-req} и выше.
. Приложение {to} {to-req} и выше.
. Модуль {wincl} {win-req} и выше.
. Модуль Служба {ws} {ws-req} и выше.
+
Требуется для полноценной работы функций модуля, включая усовершенствованное согласование.
+
Если _Служба {ws}_ устанавливается отдельно от сервера {dv}, потребуется указать адрес сервера {dv} и соответствующие настройки в конфигурационном файле Службы.
include::admin:update-module.adoc[tags=warning]

[#license]
== Лицензия

Для работы с модулем _{ad}_ лицензия на систему {dv} должна содержать дополнительную опцию: _{dv} Approval Designer_.

При отсутствии лицензии в модуле теряется возможность создания расширенных согласований. При попытке создать новые карточки _Этап согласования_ и _Маршрут согласования_ будет выдано сообщение об ошибке: `Лицензия не позволяет работать с конструктором согласований`. При этом, если лицензия отсутствует, возможность работы с ранее созданными маршрутами и этапами согласований сохраняется. Конечные пользователи смогут отправлять задания на согласования по настроенным маршрутам.
