= Требования для установки модуля

== Необходимое техническое обеспечение

Специальные требования к аппаратному обеспечению клиентского и серверного компьютера не предъявляются.

== Требования серверной части Модуля

. *Модули {dv}*:
[loweralpha]
.. Серверная часть модуля "{dv} 5. Платформа" версии 5.5.2 сборка 4553 и выше.
.. Серверная часть модуля "{dv} 5. Базовые объекты" версии 5.5.3 сборка 5367 и выше.
.. Серверная часть приложения "{dv} 5. {ud}" версии 5.5.3 сборка 5316 и выше.
.. Серверная часть модуля "{dv} 5. Управление процессами" версии 5.5.2 сборка 4224 и выше.
.. Серверная часть приложения "{dv} 5. Делопроизводство 4.5" версии 5.5.2 сборка 4203 и выше.
.. Серверная часть модуля "{dv} 5. Windows-клиент" версии 5.5.2 сборка 4248 и выше.

== Требования клиентской части Модуля

. *Модули {dv}*:
[loweralpha]
.. Клиентская часть модуля "{dv} 5. Платформа" версии 5.5.2 сборка 4553 и выше.
.. Клиентская часть модуля "{dv} 5. Базовые объекты" версии 5.5.3 сборка 5367 и выше.
.. Клиентская часть приложения "{dv} 5. {ud}" версии 5.5.3 сборка 5316 и выше.
.. Клиентская часть модуля "{dv} 5. Управление процессами" версии 5.5.2 сборка 4224 и выше.
.. Клиентская часть приложения "{dv} 5. Делопроизводство 4.5" версии 5.5.2 сборка 4203 и выше.
.. Клиентская часть модуля "{dv} 5. Windows-клиент" версии 5.5.2 сборка 4248 и выше.

== Лицензия

Для работы с модулем "{ad}" лицензия на систему {dv} должна содержать дополнительную опцию: "{dv} Approval Designer".

При отсутствии лицензии в Модуле теряется возможность создания расширенных согласований. При попытке создать новые карточки Этап согласования и Маршрут согласования будет выдано сообщение об ошибке: "Лицензия не позволяет работать с конструктором согласований". При этом, при отсутствии лицензии сохраняется возможность работы с ранее созданными маршрутами/этапами согласований -- _конечные пользователи_ смогут отправлять задания на согласования по настроенным маршрутам.

