= Роли пользователей

Модуль _{ad}_ добавляет в систему {dv} пользовательские роли для определения права доступа к документам и возможности выполнения операций с карточками.

.Общие роли:
. Администратор КС -- сотрудник, выполняющий настройку системы, разрабатывающий этапы и маршруты согласования. Входит в группу _Справочника сотрудников_ "xref:admin:create-admin.adoc[{dv-ad-admins-dir}]".
. Инициатор согласования -- сотрудник, работающий с документами, инициирующий и управляющий согласованием.
. Участник согласования -- сотрудник, получающий задание на согласование: согласующий, консолидатор и другие.

[#admins]
[start=4]
.Роли карточки "Этап согласования":
. {dv-ad-admins-dir} -- сотрудники, разрабатывающие этапы и маршруты согласования. Администраторы должны входить в группу _Справочника сотрудников_ "xref:admin:create-admin.adoc[{dv-ad-admins-dir}]".

[start=5]
.Роли карточки "Маршрут согласования":
. {dv-ad-admins-dir} -- см. описание роли <<admins,выше>>.

[start=6]
.Роли карточки "Согласование КС":
. _Инициатор_ -- сотрудник, который инициировал процесс согласования или управляет запущенным согласованием.
. _{dv-ad-admins-dir}_ -- см. описание роли <<admins,выше>>. Роль используется для xref:admin:approval-view-business-process.adoc[операции] Просмотр бизнес-процесса из карточки "Согласование КС".
. Читатели документа -- сотрудники, являющиеся получателями документов, подписывающими и согласующими, а также заместителями и руководителями этих лиц и регистратора документа, по которому было создано согласование.
. Участник согласования -- сотрудник, участвующий в исполнении заданий, разосланных в ходе выполнения согласования документа, а также его временные и постоянные заместители.

[start=10]
.Роли карточек "Задание КС/На консолидацию, подписание, согласование":
. _Автор_ -- инициатор согласования, который отправил задание на консолидацию из карточки вида _Согласование КС_, а также его постоянный и временный заместители.
. _Исполнитель_ -- сотрудник, который получил задание на консолидацию документа, а также его постоянный и временный заместители.
. _Делегировавший_ -- сотрудник, который выполнил делегирование задания на консолидацию другому исполнителю.
. _Все руководители_ -- все вышестоящие руководители автора и исполнителя задания, а также временных и постоянных заместителей автора и исполнителя задания.
