= Уровень подготовки пользователя

Для эксплуатации модуля _{ad}_ определены две пользовательские роли: администратор {dv} и (конечный) пользователь. На этапе внедрения системы {dv} в организации появляются дополнительные роли: инженер и разработчик {dv}.

Администратор {dv} устанавливает модуль и выявляет неполадки в работе бизнес-процессов согласования. Администратор {dv} должен обладать навыками настройки модуля _{pl}_, формирования сертификатов ЭП, использования криптопровайдера "КриптоПро"; а также ознакомиться с xref:5.5.5@backoffice:admin:install.adoc[документацией по администрированию] модуля {bo}.

Пользователь {dv} отправляет документы на согласование и участвует в их согласовании. Основным пользовательским рабочим местом является xref:5.5.17@webclient:user:launch.adoc[{wc}]. Все пользователи модуля должны обладать базовыми навыками работы на персональном компьютере и в интернет браузере. Пользователям необходимо ознакомиться с xref:5.5.4@documentmgmt:user:preparation.adoc[документацией по работе с модулем {dm}].

Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}. Инженер {dv} настраивает шаблоны, этапы и маршруты согласования, конфигурирует Службу {ws}.

При необходимости разработки собственных скриптов, маршрутов и сценариев согласования и функций БП разработчик {dv} занимается их разработкой. Програмист должен иметь опыт разработки на любом из языков платформы .NET: C# или Visual Basic .NET, а также ознакомиться с xref:dv5@programmer::index.adoc[{dv} 5.5. Руководством разработчика].
