= Уровень подготовки пользователя

Для эксплуатации модуля "{ad}" определены две пользовательские роли: администратор {dv} и конечный пользователь. На этапе внедрения системы {dv} в организации появляется дополнительные роли: инженер и программист {dv}.

Администратор {dv} устанавливает серверную часть Модуля, выявляет неполадки в работе бизнес-процессов согласования.

Пользователь отправляет документы на согласование и участвует в согласовании документов.

Инженер {dv} настраивает шаблоны, этапы и маршруты согласования.

Все пользователи Модуля должны обладать базовыми навыками работы на персональном компьютере, в "Windows-клиенте" (модуль "{dv} 5. Windows-клиент").

Пользователям необходимо ознакомиться с руководством пользователя модуля "{dv} 5. {ud}".

Администратор {dv} должен обладать навыками настройки модуля "{dv} 5. Платформа", формирования сертификатов ЭЦП в ОС Windows, использования криптопровайдера "КриптоПро"; а также ознакомиться с документом _Модуль "{dv} 5. Базовые объекты". Руководство администратора_.

Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}.

Программист должен иметь опыт разработки на языке C# или Visual Basic .NET, а также ознакомиться с документом _{dv} 5.5. Руководство программиста_.
