= Уровень подготовки пользователя

Для эксплуатации модуля _{ad}_ определены две пользовательские роли: администратор {dv} и конечный пользователь. На этапе внедрения системы {dv} в организации появляется дополнительные роли: инженер и программист {dv}.

Администратор {dv} устанавливает серверную часть модуля, выявляет неполадки в работе бизнес-процессов согласования.

Пользователь отправляет документы на согласование и участвует в согласовании документов.

Инженер {dv} настраивает шаблоны, этапы и маршруты согласования.

Все пользователи модуля должны обладать базовыми навыками работы на персональном компьютере, в "_{wincl}е_" (модуль _{wincl}_).

Пользователям необходимо ознакомиться с руководством пользователя модуля _{dm}_.

Администратор {dv} должен обладать навыками настройки модуля _{pl}_, формирования сертификатов ЭП в ОС Windows, использования криптопровайдера "КриптоПро"; а также ознакомиться с руководством по администрированию модуля {bo}.

Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}.

Программист должен иметь опыт разработки на языке C# или Visual Basic .NET, а также ознакомиться с документом _{dv} 5.5. Руководство программиста_.