= Уровень подготовки пользователя

Для эксплуатации модуля _{ad}_ определены две пользовательские роли: администратор {dv} и конечный пользователь. На этапе внедрения системы {dv} в организации появляется дополнительные роли: инженер и программист {dv}.

Администратор {dv} устанавливает серверную часть модуля, выявляет неполадки в работе бизнес-процессов согласования. Администратор {dv} должен обладать навыками настройки модуля _{pl}_, формирования сертификатов ЭП в ОС Windows, использования криптопровайдера "КриптоПро"; а также ознакомиться с xref:backoffice:admin:install.adoc[документацией по администрированию] модуля {bo}.

Пользователь {dv} отправляет документы на согласование и участвует в их согласовании. Основным пользовательским рабочим местом является {wc}. Все пользователи модуля должны обладать базовыми навыками работы на персональном компьютере и в интернет браузере. Пользователям необходимо ознакомиться с xref:5.5.4@documentmgmt:user:preparation.adoc[документацией по работе с модулем {dm}].

Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}. Инженер {dv} настраивает шаблоны, этапы и маршруты согласования.

При необходимости разработки собственных скриптов (сценариев) и функций БП программист {dv} занимается их разработкой. Програмист должен иметь опыт разработки на любом из языков платформы .NET: C# или Visual Basic .NET, а также ознакомиться с xref:dv5@programmer:index.adoc[{dv} 5.5. Руководством разработчика].
