[[ariaid-title1]]
== Настройка этапов согласования

Настройка этапов согласования является необходимым условием создания расширенного согласования. Этап позволяет задавать xref:StageParams_common.adoc[тип согласования], определять xref:StageParams_reconcilers.adoc[состав согласующих] лиц, набор принимаемых ими xref:StageParams_task_decisions.adoc[решений], задавать специальные настройки xref:StageParams_task.adoc[заданий] и xref:StageParams_extra.adoc[дополнительные] параметры согласования.

[.dfn .term]_Конструктор согласований_ предусматривает настройку расширенных согласований следующих основных xref:StageParams_common.adoc[типов]:

* [.keyword .parmname]_Согласование_ - тип предназначен для принятия решения при согласовании, подписании или утверждении документов, с возможностью просмотра, редактирования и создания собственных версий согласуемых документов (файлов).
* [.keyword .parmname]_Подписание_ - тип предназначен для принятия решения и наложения согласующих подписей при согласовании, подписании или утверждении документов, с возможностью просмотра, редактирования и создания собственных версий согласуемых документов (файлов).
* [.keyword .parmname]_Консолидация_ - тип предназначен для создания итоговой версии согласуемого документа (файла) путем сравнения версий, добавленных согласующими.

Для данных типов согласований предусмотрены следующие варианты маршрутизации:

* [.keyword .parmname]_Последовательный_;
* [.keyword .parmname]_Параллельный_;
* [.keyword .parmname]_Альтернативный_.

Этап согласования позволяет задать нужный тип согласования, определить способ маршрутизации и выполнить его настройку в соответствии с конкретными задачами документооборота. Возможно использование любых комбинаций режима согласования и типа маршрутизации.

Из созданных этапов затем выполняется формирование xref:Approval_path.adoc[маршрутов] согласования. Маршрут может включать любое количество этапов. Допускается также вариант, когда этап создан, но не добавлен ни в один маршрут.

При формировании маршрута, для каждого из этапов при помощи инструмента [.dfn .term]_Конструктор условий_ (входящего в состав [.dfn .term]_Конструктора согласований_) настраиваются xref:Start_conditions.adoc[условия старта].

* *xref:../pages/StageCard_create.adoc[Создание карточки 'Этап согласования']* +
* *xref:../pages/StageParams.adoc[Параметры этапа]* +
* *xref:../pages/StageParams_task.adoc[Настройки заданий]* +
* *xref:../pages/StageParams_extra.adoc[Дополнительные настройки]* +

*На уровень выше:* xref:../pages/Engineer_functions.adoc[Настройка согласований]
