[[ariaid-title1]]
== Настройка маршрутов согласования

Маршрут согласования предназначен для объединения этапов в группы, определения условий старта этапов и других параметров.

В процессе согласования документа маршрут может быть пройден несколько раз, при этом каждая новая итерация прохождения маршрута будет называться циклом. Переход от текущего цикла к последующему и завершение цикла выполняется по определенным xref:Approving_finish.adoc[правилам].

Маршрут может включать как этапы, настроенные для выполнения xref:StageCard_create_approval.adoc[согласования], так и этапы для выполнения xref:StageCard_create_consolidation.adoc[консолидации]. Главной задачей при настройке маршрута является xref:Path_roadmap.adoc[настройка] [.keyword]*Карты этапов* и xref:Path_DocFinalState.adoc[финальных состояний] документов.

При старте согласования, выбор маршрута определяется настройками xref:TemplateCard_create.adoc[шаблона] согласования.

* *xref:../pages/PathCard_create.adoc[Создание карточки 'Маршрут согласования']* +
* *xref:../pages/Path_roadmap.adoc[Формирование карты этапов]* +
* *xref:../pages/Path_roadmap_delete.adoc[Удаление этапа из маршрута]* +
* *xref:../pages/Path_roadmap_stage_view.adoc[Открытие карточки 'Этап согласования' из 'Карты этапов']* +
* *xref:../pages/Path_DocFinalState.adoc[Настройка итогового состояния документа]* +

*На уровень выше:* xref:../pages/Engineer_functions.adoc[Настройка согласований]
