[[ariaid-title1]]
== Настройка безопасности

Перед началом работы с Модулем необходимо назначить администратора [.dfn .term]_Конструктора согласований_ (администратор КС) – пользователя, которому будут предоставлено право настраивать согласования. Администраторам КС предоставляется полный доступ к типам карточек [.dfn .term]_Этап согласования_ и [.dfn .term]_Маршрут согласования_.

. [.ph .cmd]#Откройте [.dfn .term]_Справочник сотрудников_.#
. [.ph .cmd]#Добавьте требуемого сотрудника в группу сотрудников «Администраторы КС».#

По умолчанию настройки видов карточек [.dfn .term]_Этап согласования_ и [.dfn .term]_Маршрут согласования_ запрещают создание экземпляров данных карточек в т.ч. администраторам КС.

[start=3]
. [.ph .cmd]#В [.dfn .term]_Справочнике видов карточек_ снимите флаги [.ph .uicontrol]*Запретить создание карточек данного вида* и [.ph .uicontrol]*Сделать вид недоступным для выбора* в настройках типов карточек: [.dfn .term]_Этап согласования_ и [.dfn .term]_Маршрут согласования_.#

*Parent topic:* xref:../pages/Administrator_functions.adoc[Функции администратора]
