= Перенос файлов из документа в согласование в процессе согласования

В процессе согласования участники могут добавлять в уже запущенное согласование новые файлы (основные или дополнительные). Возможность добавлять файлы определяется настройками _ролевой модели_ для вида документа. По умолчанию, данная возможность в модуле отключена.

.Чтобы настроить возможность добавлять файлы в запущенное согласование:
. Откройте _Конструктор состояний_. Для состояний `На согласовании`, `На подписании` в поле _Доступность_ установите флаги напротив операций редактирования _Добавление основного файла_, _Добавление дополнительного файла_. Сохраните изменения.
. Откройте _Конструктор ролей_.
+
* В поле _Библиотека карточек_ выберите значение _{bo}_.
* В поле _Вид документа_ установите вид, из карточек которого можно будет добавлять файлы в процессе согласования.
+
. Перейдите на вкладку _Матрица доступа_. В поле _Объект_ выберите роль, для которой будут выполняться настройки, например, _Участник задания по документу_.
+
Для операций _Добавление основного файла_, _Добавление дополнительного файла_ установите разрешения в состояниях _на согласовании_, _на подписании_.
+
В результате выполненных действий, при переходе в карточку _ДокументУД_, полученную в задании на согласование, у определённых ролей. В данном примере -- у роли _Участник задания по документу_ после перехода в режим редактирования карточки будут доступны операции добавления основных и дополнительных файлов.
+
.После сохранения изменений, добавленные файлы будут перенесены в задание на согласование:
* Основной файл -- в область _Версии и комментарии_, на новую вкладку.
* Дополнительный файл -- в область _Дополнения_.
+
Добавленные файлы будут доступны согласующим после перехода к следующему этапу согласования.
