[[ariaid-title1]]
== Роли пользователей

Модуль «Конструктор согласований» добавляет в систему Docsvision пользовательские роли для определения права доступа к документам и возможности выполнения операций с карточками.

. Общие роли:
[loweralpha]
.. Администратор КС – сотрудник, выполняющий настройку системы, разрабатывающий этапы и маршруты согласования; входит в группу [.dfn .term]_Справочника сотрудников_ xref:ConfigureSecurity.html[[.keyword]*Администраторы КС*].
.. Инициатор согласования – сотрудник, работающий с документами, инициирующий и управляющий согласованием.
.. Участник согласования – сотрудник, получающий задание на согласование (согласующий, консолидатор и др.).
. Роли карточки [.dfn .term]_Этап согласования_:
[loweralpha]
.. Администраторы КС – сотрудники, разрабатывающие этапы и маршруты согласования; входят в группу [.dfn .term]_Справочника сотрудников_ link:ConfigureSecurity.html[[.keyword]*Администраторы КС*].
. Роли карточки [.dfn .term]_Маршрут согласования_:
[loweralpha]
.. Администраторы КС (см. описание роли выше).
. Роли карточки [.dfn .term]_Согласование КС_:
* Инициатор – сотрудник, который инициировал процесс согласования или управляет запущенным согласованием.
* Администраторы КС (см. описание роли выше). Роль используется для операции link:Business_process_open.adoc[Просмотр бизнес-процесса из карточки 'Согласование КС'];
* Читатели документа – сотрудники, являющиеся получателями документов, подписывающими и согласующими, а также заместителями и руководителями этих лиц и регистратора документа, по которому было создано согласование;
* Участник согласования – сотрудник, участвующий в исполнении заданий, разосланных в ходе выполнения согласования документа, а также его временные и постоянные заместители.
. Роли карточки [.dfn .term]_Задание КС/На консолидацию_:
[loweralpha]
.. Автор – инициатор согласования, который отправил задание на консолидацию из карточки вида [.dfn .term]_Согласование КС_, а также его постоянный и временный заместители.
.. Исполнитель – сотрудник, который получил задание на консолидацию документа, а также его постоянный и временный заместители.
.. Делегировавший – сотрудник, который выполнил делегирование задания на консолидацию другому исполнителю.
.. Все руководители – все вышестоящие руководители автора и исполнителя задания, а также их (автора и исполнителя) временных и постоянных заместителей.
. Роли карточки [.dfn .term]_Задание КС/На подписание_:
[loweralpha]
.. Автор – инициатор согласования, который отправил задание на подписание из карточки вида [.dfn .term]_Согласование КС_, а также его постоянный и временный заместители.
.. Исполнитель – сотрудник, который получил задание на подписание документа, а также его постоянный и временный заместители.
.. Делегировавший – сотрудник, который выполнил делегирование задания на подписание другому исполнителю.
.. Все руководители – все вышестоящие руководители автора и исполнителя задания, а также их (автора и исполнителя) временных и постоянных заместителей.
. Роли карточки [.dfn .term]_Задание КС/На согласование_:
[loweralpha]
.. Автор – инициатор согласования, который отправил задание на согласование из карточки вида [.dfn .term]_Согласование КС_, а также его постоянный и временный заместители.
.. Исполнитель – сотрудник, который получил задание на согласование документа, а также его постоянный и временный заместители.
.. Делегировавший – сотрудник, который выполнил делегирование задания на консолидацию другому исполнителю.
.. Все руководители – все вышестоящие руководители автора и исполнителя задания, а также их (автора и исполнителя) временных и постоянных заместителей.

*Parent topic:* xref:../pages/Structureof_program.adoc[Структура Модуля]
