= Усовершенствованное согласование

Усовершенствованное согласование меняет поведение элементов управления в карточках согласования и заданиях согласования.

Чтобы включить усовершенствованное согласование, необходимо установить соответствующий флаг при создании нового маршрута.

.Усовершенствованное согласование:
* Не используется, если флаг `*Усовершенствованное согласование*` не установлен. Согласование будет запущено в соответствии с обычной логикой.
* Используется, если флаг `*Усовершенствованное согласование*`  установлен. Логика работы согласования будет изменена в соответствии с описанными ниже правилами.

== Передача версий между этапами

При каждом изменении документа создаётся новая версия. Если документ не был изменён, новая версия не создаётся. Каждая версия привязывается к этапу, на котором она сформирована.

Учитывая, что в рамках одного цикла этапы могут быть запущены несколько раз, на следующий этап переходит только итоговая версия текущего с учётом всех повторных запусков.

В дереве версий будет создана новая версия, только если файл был изменён.

== Условия завершения маршрута

Для усовершенствованного маршрута существует возможность настроить условие завершения маршрута.

Отдельно можно настроить условия для положительного и для отрицательного завершения этапа при помощи следующих настроек:

_Условия для положительного или отрицательного завершения маршрута_ -- задаются аналогично xref:route-stage-conditions.adoc[настройке] условий старта этапа в карте этапов.

В усовершенствованном маршруте _Таблица настройки итоговых состояний_ будет видоизменена. В таблице появится дополнительная колонка, позволяющая выбрать _Состояние при отрицательном завершении_. Колонка _Состояние_ будет переименована в _Состояние при положительном завершении_.

Настройки усовершенствованного маршрута не являются обязательными к заполнению и любую из них или обе можно не указывать.
