= Усовершенствованное согласование

Усовершенствованное согласование меняет поведение элементов управления в карточках согласования и заданиях согласования.

Чтобы включить усовершенствованное согласование, необходимо установить соответствующий флаг при создании нового маршрута.

.Усовершенствованное согласование:
* Не используется, если флаг `*{um}*` не установлен. Согласование будет запущено в соответствии с обычной логикой.
* Используется, если флаг `*{um}*`  установлен. Логика работы согласования будет изменена в соответствии с описанными ниже правилами.

[#first]
== "Первый" этап

Первым можно назначить один или несколько этапов. По умолчанию флаг `*Первый*` устанавливается для этапа в верхней строке. Для первого этапа можно xref:route-stage-conditions.adoc[задать] условия старта.

[#repeat]
== Повтор этапа

{um} позволяет повторять этап в цикле несколько раз. Настроить повторение этапа можно в xref:route-map.adoc[карте этапов] маршрута согласования.

include::partial$excerpts.adoc[tags=repeat]

include::partial$excerpts.adoc[tags=save-stage]

== Передача версий между этапами

При каждом изменении документа создаётся новая версия. Если документ не был изменён, новая версия не создаётся. Каждая версия привязывается к этапу, на котором она сформирована.

Учитывая, что в рамках одного цикла этапы могут быть запущены несколько раз, на следующий этап переходит только итоговая версия текущего с учётом всех повторных запусков.

В дереве версий будет создана новая версия, только если файл был изменён.

[#completion]
== Условия завершения маршрута

Для усовершенствованного маршрута существует возможность настроить условие завершения маршрута.

Отдельно можно настроить условия для положительного и для отрицательного завершения этапа при помощи следующих настроек:

_Условия для положительного или отрицательного завершения маршрута_ -- задаются аналогично xref:route-stage-conditions.adoc[настройке] условий старта этапа в карте этапов.

В усовершенствованном маршруте _Таблица настройки итоговых состояний_ будет видоизменена. В таблице появится дополнительная колонка, позволяющая выбрать _Состояние при отрицательном завершении_. Колонка _Состояние_ будет переименована в _Состояние при положительном завершении_.

Настройки усовершенствованного маршрута не являются обязательными к заполнению и любую из них или обе можно не указывать.
