= Усовершенствованное согласование

[WARNING]
====
include::partial$excerpts.adoc[tags=manual-delete]
====

Усовершенствованное согласование меняет поведение элементов управления в карточках согласования и заданиях согласования.

Чтобы включить усовершенствованное согласование, необходимо установить соответствующий флаг при создании нового маршрута.

.Усовершенствованное согласование:
* Не используется, если флаг `*{um}*` не установлен. Согласование будет запущено в соответствии с обычной логикой.
* Используется, если флаг `*{um}*` установлен. Логика работы согласования будет изменена в соответствии с описанными ниже правилами.

[NOTE]
====
Возможность создать маршрут согласования с обычной логикой остаётся доступной.

При этом любые настройки, связанные с усовершенствованным маршрутом должны отсутствовать в этапах, иначе маршрут с обычной логикой не будет работать. При работе обычных маршрутов настройки усовершенствованных не учитываются.
====

include::partial$excerpts.adoc[tags=save-stage]

****
Усовершенствованные маршруты согласования хранятся в папке _Усовершенствованное согласование_ и предназначены для карточек модуля _{dm}_. Усовершенствованные маршруты из указанной папки не будут работать, если модуль _{dm}_ не установлен. В таком случае необходимо настраивать маршруты самостоятельно.
****

[#first]
== "Первый" этап

Первым можно назначить один или несколько этапов. По умолчанию флаг `*Первый*` устанавливается для этапа в верхней строке. Для первого этапа можно xref:route-stage-conditions.adoc[задать] условия старта.

[#repeat]
== Условия повторения этапа

Один этап усовершенствованного согласования может повторяться внутри цикла, если предыдущий этап завершился определённым образом.

.Условия состоят из:
* Элементов условий -- одна строка.
+
Элемент условия выполняется, если указанный в нем этап завершился с указанным вариантом.
+
* Групп условий -- несколько строк, объединённых под `И`/`ИЛИ`. Группа может объединять несколько элементов или несколько групп.
+
Группа условий выполняется, если выполнены *обязательные* элементы.

В дополнение к xref:stage-finish-settings.adoc[существующим] настройкам завершения предыдущего этапа {us} позволяет настроить следующие:

* *_Не отрицательное_* -- выполняется если этап завершён Положительно или Условно-положительно.
* *_Любое_* -- выполняется если этап завершён Положительно, Условно-положительно или Отрицательно.

Если при повторе по какой-то причине вариант окажется пропущен, в согласовании будет учитываться результат последнего из предыдущих экземпляров этого этапа.

Если этап завершился с семантикой "Вернуть на предыдущий этап", предыдущий этап должен стартовать, не принимая во внимание никакие условия старта

Также этап может быть исключён из маршрута при старте или в процессе согласования. Исключенный этап не стартует, а считается завершённым сразу, как выполнены условия его старта. В таком случае будет учтён предыдущий результат этапа. Если этап ещё ни разу не выполнялся в этом цикле, будет учтён "результат завершения по умолчанию" из настроек этапа.

При повторе этапов также учитывается настройка в xref:route-map.adoc[карте этапов].

.В карте для этапа могут быть заданы следующие настройки:
include::partial$excerpts.adoc[tags=repeat]

Повторный запуск этапов на новых циклах можно отключить, установив флаг `*Пропускать этап при повторе на новом цикле*`. В таком случае будет использован результат выполнения из предыдущего экземпляра этапа. Результат первичного завершения данного этапа будет использован в дальнейшем ходе согласования.

[#autocomplete]
== Автоматическое завершение цикла

Цикл завершается автоматически, если нет ни одного незавершённого экземпляра этапа и ни одного выполняемого на текущий момент условия старта в карте этапов этого маршрута.
Если все последние экземпляры каждого этапа завершены положительно или условно-положительно, завершается положительно весь маршрут.

Если среди последних экземпляров этапов есть завершённые отрицательно, будет запущен новый цикл.

[#stage-to-stage]
== Передача версий между этапами

При каждом изменении документа создаётся новая версия. Если документ не был изменён, новая версия не создаётся. Каждая версия привязывается к этапу, на котором она сформирована.

Учитывая, что в рамках одного цикла этапы могут быть запущены несколько раз, на следующий этап переходит только итоговая версия текущего с учётом всех повторных запусков.

В дереве версий будет создана новая версия, только если файл был изменён.

[#completion]
== Условия завершения маршрута

Для усовершенствованного маршрута существует возможность настроить условие завершения маршрута.

Отдельно можно настроить условия для положительного и для отрицательного завершения этапа при помощи следующих настроек:

_Условия для положительного или отрицательного завершения маршрута_ -- задаются аналогично xref:route-stage-conditions.adoc[настройке] условий старта этапа в карте этапов.

В усовершенствованном маршруте _Таблица настройки итоговых состояний_ будет видоизменена. В таблице появится дополнительная колонка, позволяющая выбрать _Состояние при отрицательном завершении_. Колонка _Состояние_ будет переименована в _Состояние при положительном завершении_.

Настройки усовершенствованного маршрута не являются обязательными к заполнению и любую из них или обе можно не указывать.
