[[ariaid-title1]]
== Поисковые слова

Руководитель инициатора::
  Будут найдены сотрудники, которые указаны в [.dfn .term]_Справочнике сотрудников_ как непосредственные руководители сотрудника, создавшего согласование из карточки вида [.keyword .parmname]_Документ УД_. Дополнительно можно настроить xref:StageParams_reconcilers.adoc[уровень иерархии] руководителя, в соответствии с которым будет осуществляться поиск.
Все руководители инициатора::
  Будут найдены сотрудники, которые указаны в [.dfn .term]_Справочнике сотрудников_ как непосредственные и вышестоящие руководители сотрудника, создавшего согласование из карточки вида [.keyword .parmname]_Документ УД_.
Инициатор::
  Будет указан сотрудник, который создал согласование из карточки [.dfn .term]_Документ_.
Регистратор::
  Будет указан сотрудник, который создал карточку вида [.keyword .parmname]_Документ УД_, и зарегистрировал документ в системе [.dfn .term]_Docsvision_.

*На уровень выше:* xref:../pages/StageParams_reconcilers.adoc[Выбор согласующих]
