[[ariaid-title1]]
== Настройка переноса файлов из документа в согласование в процессе согласования

При выполнении согласования у участников согласования имеется возможность добавления в уже запущенное согласование новых файлов (основных или дополнительных). Возможность добавления файлов определяется настройками [.dfn .term]_ролевой модели_ для вида документа. По умолчанию, данная возможность в модуле отключена.

Чтобы настроить возможность добавления файлов в запущенное согласование, выполните следующие действия:

. [.ph .cmd]#Откройте [.dfn .term]_Конструктор состояний_. Для состояний [.keyword .parmname]_на согласовании_, [.keyword .parmname]_на подписании_ в поле [.keyword]*Доступность* установите флаги напротив операций редактирования [.keyword .parmname]_Добавление основного файла_, [.keyword .parmname]_Добавление дополнительного файла_. Сохраните изменения.#
. [.ph .cmd]#Откройте [.dfn .term]_Конструктор ролей_. В поле [.keyword]*Библиотека карточек* выберите значение [.keyword .parmname]_Базовые объекты_. В поле [.keyword]*Вид документа* установите вид, из карточек которого можно будет выполнять добавление файлов в процессе согласования. #
. [.ph .cmd]#Перейдите на вкладку [.keyword]*Матрица доступа*. В поле [.keyword]*Объект* выберите роль, для которой будут выполняться настройки (например, [.keyword .parmname]_Участник задания по документу_. Для операций [.keyword .parmname]_Добавление основного файла_, [.keyword .parmname]_Добавление дополнительного файла_ установите разрешения в состояниях [.keyword .parmname]_на согласовании_, [.keyword .parmname]_на подписании_.#
+
В результате выполненных действий, при переходе в карточку [.keyword .parmname]_ДокументУД_, полученную в задании на согласование, у определенных ролей (в нашем примере - у роли [.keyword .parmname]_Участник задания по документу_) после перехода в режим редактирования карточки будут доступны операции добавления основных и дополнительных файлов.

После сохранения изменений, добавленные файлы будут перенесены в задание на согласование:

* основной файл - в область [.keyword]*Версии и комментарии*, на новую вкладку;
* дополнительный файл - в область [.keyword]*Дополнения*.

Добавленные файлы будут доступны согласующим после перехода к следующему этапу согласования.

*На уровень выше:* xref:../pages/Engineer_functions.adoc[Настройка согласований]
