= Настройка переноса файлов из документа в согласование в процессе согласования

При выполнении согласования у участников согласования имеется возможность добавления в уже запущенное согласование новых файлов (основных или дополнительных). Возможность добавления файлов определяется настройками _ролевой модели_ для вида документа. По умолчанию, данная возможность в модуле отключена.

Чтобы настроить возможность добавления файлов в запущенное согласование:

. Откройте _Конструктор состояний_. Для состояний _на согласовании_, _на подписании_ в поле *Доступность* установите флаги напротив операций редактирования _Добавление основного файла_, _Добавление дополнительного файла_. Сохраните изменения.
. Откройте _Конструктор ролей_. В поле *Библиотека карточек* выберите значение _Базовые объекты_. В поле *Вид документа* установите вид, из карточек которого можно будет выполнять добавление файлов в процессе согласования.
. Перейдите на вкладку *Матрица доступа*. В поле *Объект* выберите роль, для которой будут выполняться настройки (например, _Участник задания по документу_. Для операций _Добавление основного файла_, _Добавление дополнительного файла_ установите разрешения в состояниях _на согласовании_, _на подписании_.
+
В результате выполненных действий, при переходе в карточку _ДокументУД_, полученную в задании на согласование, у определенных ролей (в нашем примере -- у роли _Участник задания по документу_) после перехода в режим редактирования карточки будут доступны операции добавления основных и дополнительных файлов.
+
.После сохранения изменений, добавленные файлы будут перенесены в задание на согласование:
* основной файл -- в область *Версии и комментарии*, на новую вкладку;
* дополнительный файл -- в область *Дополнения*.
+
Добавленные файлы будут доступны согласующим после перехода к следующему этапу согласования.
