[[ariaid-title1]]
== Настройка управления согласованием для консолидатора

У пользователя, выполняющего консолидацию, имеется возможность открытия карточки активного согласования. Однако, если Консолидатор не является одновременно Инициатором согласования, карточка будет открыта в режиме чтения. При необходимости, возможность управления согласованием может быть настроена для любого сотрудника.

Чтобы настроить возможность управления согласованием для консолидатора, выполните следующие действия:

. [.ph .cmd]#В [.dfn .term]_Конструкторе ролей_ добавьте новую роль (роль для карточки вида [.dfn .term]_Согласование КС_ или дополнительное условие по ИЛИ к существующей роли [.keyword]*Инициатор*).#
. [.ph .cmd]#Разработайте хранимую процедуру для созданной роли, в результате выполнения которой станет известен текущий исполнитель задания на консолидацию. #
. [.ph .cmd]#В [.dfn .term]_Конструкторе ролей_ предоставьте роли, найденной на предыдущем шаге, права на операцию редактирования «Кнопки редактирования маршрута».#

*На уровень выше:* xref:../pages/Engineer_functions.adoc[Настройка согласований]
