= Настройка этапов согласования

Настройка этапов согласования является необходимым условием создания расширенного согласования. Этап позволяет задавать xref:stage-name.adoc[тип согласования], определять xref:stage-approvers.adoc[состав согласующих] лиц, набор принимаемых ими xref:task-decisions.adoc[решений], задавать специальные настройки xref:stage-task.adoc[заданий] и xref:stage-additional-settings.adoc[дополнительные] параметры согласования.

._{ad}_ предусматривает настройку расширенных согласований следующих основных xref:StageParams_common.adoc[типов]:
* _Согласование_ -- тип предназначен для принятия решения при согласовании, подписании или утверждении документов, с возможностью просмотра, редактирования и создания собственных версий согласуемых документов (файлов).
* _Подписание_ -- тип предназначен для принятия решения и наложения согласующих подписей при согласовании, подписании или утверждении документов. На этапе предусматривается возможность просмотра, редактирования и создания собственных версий согласуемых документов (файлов).
* _Консолидация_ -- тип предназначен для создания итоговой версии согласуемого документа (файла) путем сравнения версий, добавленных согласующими.

.Для данных типов согласований предусмотрены следующие варианты маршрутизации:
* *_Последовательный_*.
* *_Параллельный_*.
* *_Альтернативный_*.

Этап согласования позволяет задать нужный тип согласования, определить способ маршрутизации и выполнить его настройку в соответствии с конкретными задачами документооборота. Допускается использовать любые комбинации режима согласования и типа маршрутизации.

Из созданных этапов формируются xref:approval-route.adoc[маршруты] согласования. Маршрут может включать любое количество этапов. Допускается также вариант, когда этап создан, но не добавлен ни в один маршрут.

При формировании маршрута, для каждого из этапов при помощи инструмента _Конструктор условий_ (входящего в состав _Конструктора согласований_) настраиваются xref:route-stage-conditions.adoc[условия старта].
