= Настройки завершения этапа

При выполнении согласования документа может возникнуть ситуация, когда заданная xref:StageParams_task_duration.adoc[длительность] этапа уже истекла, а согласования документа не произошло. Чтобы избежать появления "зависших" этапов используются специальные настройки завершения.

[NOTE]
====
Для исключения "зависших" заданий используются настройки xref:StageParams_task_auto_approval.adoc[автосогласования].
====

.Чтобы настроить параметры завершения этапа:
. Создайте новую или откройте существующую карточку _Этап согласования_.
. Перейдите на вкладку xref:StageParams_extra.adoc[Дополнительные настройки].
. Найдите область *Завершение этапа*
. Чтобы этапы, в которых отсутствуют заданные исполнители, или xref:Start_conditions.adoc[исключенные] из маршрута инициатором согласования, завершались с определенным вариантом решения, выберите требуемую семантику в поле *Семантика завершения этапа по умолчанию*.
+
Настройка необходима для сохранения целостности маршрута и корректной обработки условий перехода между этапами. По умолчанию для этапов с отсутствующими исполнителями будет использоваться положительная семантика решения.
+
. Чтобы после завершения этапа запускался определенный бизнес-процесс, в поле *По завершении этапа запускать бизнес-процесс* выберите название требуемого бизнес-процесса.
+
Например, после завершения этапа можно запустить бизнес-процесс рассылки уведомлений.
+
Данный бизнес-процесс будет запущен от имени учетной записи, под которой запущено приложение _Управление процессами_ (_Workflow_). Для корректной работы бизнес-процесса в его настройках безопасности должны быть выданы права на чтение для группы *Системная для WF*.
+
Если для указанного бизнес-процесса создать переменные того же вида и с таким же названием, как и в процессе xref:ROOT:business-processes.adoc[*КС Основной процесс*], а также в дополнительных свойствах этих переменных снять флаг *Скрыта от родительского процесса*, то при старте выбранного произвольного процесса значения таких переменных будут скопированы из родительского процесса.
+
Завершение бизнес-процессов xref:ROOT:business-processes.adoc[*КС Последовательное согласование*] и xref:ROOT:business-processes.adoc[*КС Параллельное согласование *] будет происходить независимо от выбранного бизнес-процесса.
+
. Чтобы избежать "зависания" согласования при выборе варианта решения с отрицательной семантикой, выберите предпочтительный вариант действий в поле *При первом отказе*:
+
* _Продолжать согласование_ -- согласование по данному этапу будет продолжено, оставшимся согласующим поступят задания на согласование текущего этапа; данный вариант настроен по умолчанию;
* _Завершать этап_ -- действия будут зависеть от xref:stage-mode.adoc[типа маршрутизации], настроенного для этапа:
** *Последовательный* -- текущий этап будет завершен с отрицательным решением, оставшимся участникам согласования текущего этапа задания на согласование разосланы не будут; будет выполнен старт следующего этапа согласования в соответствии с маршрутом;
** *Параллельный* -- текущий этап будет завершен с отрицательным решением; незавершенные задания остальных участников согласования будут отозваны; на вкладке *Ход согласования* для данного этапа будут изменены значения строк, соответствующих отозванным заданиям (в столбец *Результат* будет записано `Отозвано`, в столбец *Комментарий к решению* записано`                                     Задание отозвано при автоматическом завершении                                     этапа`, в столбец *Дата* записаны дата и время отзыва задания).
* _Завершать согласование_ -- действия будут зависеть от xref:stage-mode.adoc[типа маршрутизации], настроенного для этапа:
** *Последовательный* -- карточка согласуемого документа будет переведена в состояние `Подготовка`; оставшимся участникам согласования текущего этапа задания на согласование разосланы не будут;
** *Параллельный* -- карточка согласуемого документа будет переведена в состояние `Подготовка`; незавершенные задания остальных участников согласования будут отозваны; на вкладке *Ход согласования* для данного этапа будут изменены значения строк, соответствующих отозванным заданиям (в столбец *Результат* будет записано `Отозвано`, в столбец *Комментарий к решению* записано `Задание отозвано при автоматическом завершении этапа`, в столбец *Дата* записаны дата и время отзыва задания);
+
Для этапов с типом маршрутизации xref:stage-mode.adoc[_Альтернативный_] такая настройка не выполняется, поле *При первом отказе* неактивно.
+
. Сохраните изменения.
