= Пропускать этап при повторе

При переходе на новый цикл согласования, некоторые этапы могут снова попасть под условие старта.

Повторный запуск этапов можно отключить, в таком случае будет использован результат выполнения этапа из предыдущего цикла.

При такой настройке последующих циклах этап не будет запущен повторно, и задания по этапу не будут разосланы участникам согласования. Результат первичного завершения данного этапа будет использован в последующих циклах, поэтому при настройке этапа следует с осторожностью использовать варианты решения *Отмена*, *Новый цикл* и *Завершение*. Также необходимо учитывать, что этап, у которого должен пропускаться при повторе, но не запускался в текущем или предыдущих циклах, будет запущен, если будут выполнены условия запуска, в следующем цикле. То есть, пропустить можно только этап, который был пройден хотя бы раз *с сохранением результатов выполнения*.

.Чтобы пропускать этап при повторе:
. Создайте новую или откройте существующую карточку этапа.
. Перейдите на вкладку _Параметры этапа_.
. Установите флаг `*Пропускать этап при повторе*`.

