= Скрыть этап в маршруте согласования

Входящие в его состав маршрута согласования этапы могут иметь различное назначение. В частности, этапы, предназначенные для служебных целей, могут быть скрыты от работающих с документами пользователей при подготовке и запуске согласования.

Администратор может скрыть этапы во время создания или редактирования карточки _Этап согласования_. При подключении маршрута согласования в xref:approval-template.adoc#template[шаблон], в поле _Состав маршрута_ администратору будет виден полный список этапов, включая скрытые.

.Чтобы скрыть этап в запущенном согласовании:
. Создайте новую или откройте существующую карточку этапа.
. Перейдите на вкладку _Параметры этапа_.
. Установите флаг в поле `*Скрыть этап*`.
+
При старте этапа у пользователя в области "xref:stage-availability.adoc#launch[Состав маршрута]" скрытые этапы будут отсутствовать.
+
В карточке активного согласования на вкладке "xref:stage-availability.adoc#active[Состав маршрута]" скрытые этапы также отображаться не будут.
+
Если этап на момент изменения активен, настройки будут применены в следующем цикле.
