[[ariaid-title1]]
== Длительность

Длительность выполнения может задаваться как для всего этапа, так и для отдельного задания.

Если длительность задается для этапа, при последовательной маршрутизации заданий длительность этапа поделится ровно между всеми участниками, а при параллельной будет равняться длительности отдельного задания. Для заданий задается длительность исполнения отдельного задания.

Допускается задание длительности выполнения как для первого прохождения этапа, так и для повторного его прохождения. Данная настройка может быть удобна для случаев, когда по окончании первого цикла согласовать документ не удалось. В этом случае, при старте нового цикла и всех последующих стартах будет использоваться другое значение длительности.

Чтобы задать длительность этапа, выполните следующие действия:

[[task_dhk_1hr_mm__steps_jgt_kfr_mm]]
. [.ph .cmd]#Создайте новую или откройте существующую карточку этапа.#
. [.ph .cmd]#Перейдите на вкладку xref:StageParams_task.adoc[Настройки заданий].#
. [.ph .cmd]#Выберите предпочтительный вариант настройки длительности при помощи выбора нужной опции: #
* [.keyword]*Длительность для задания*;
* [.keyword]*Длительность для этапа*.
. [.ph .cmd]#В поле [.keyword]*Длительность (часы)* укажите время в часах, в течение которого должно быть выполнено задание/этап. Длительность вычисляется согласно xref:StageParams_task_calendar.adoc[бизнес-календарю].#
. [.ph .cmd]#Если требуется указать длительность выполнения этапа при последующих проходах, установите флаг в поле [.keyword]*В следующих циклах* и в соседнем поле укажите количество выделенных часов.#

Настроенная длительность будет отображаться в [.keyword]*Карте этапов* карточки [.keyword .parmname]_Маршрут согласования_.

Чтобы исключить появление заданий с истекшей длительностью, рекомендуется настроить xref:StageParams_task_auto_approval.adoc[Автоматическое завершение заданий].

*На уровень выше:* xref:../pages/StageParams_task.adoc[Настройки заданий]
