= Пропуск этапа при повторе

При переходе на новый цикл согласования, некоторые этапы могут снова попасть под условие старта. Повторный запуск этапов можно отключить, при этом будет зачтен результат выполнения этапа из предыдущего цикла. При такой настройке фактического запуска этапа в последующих циклах не произойдет, и задания по этапу не будут разосланы участникам согласования. Результат первичного завершения данного этапа будет использован в последующих циклах, поэтому при настройке этапа следует с осторожностью использовать варианты решения *Отмена*, *Новый цикл* и *Завершение*. Также необходимо учитывать, что этап, у которого включен пропуск при повторе, но который не запускался в текущем или предыдущих циклах, будет запущен (при выполнении условий запуска) в следующем цикле, т.к. для возможности пропуска этапа он должен быть пройден хотя бы раз *с сохранением результатов выполнения*.

.Чтобы настроить пропуск этапа при повторе, выполните следующие действия:
. Создайте новую или откройте существующую карточку этапа.
. Перейдите на вкладку *Параметры этапа*.
. Установите флаг в поле *Пропускать этап при повторе*.

