= Режим и тип маршрутизации

Параметры _Режим_ и _Тип маршрутизации_ обязательно должны быть заполнены при настройке этапа. _Режим_ отображается в названии заданий и определяет выбор сценария работы заданий. Параметр _Тип маршрутизации_ определяет способ рассылки заданий участникам согласования на данном этапе. При настройке допускаются любые комбинации использования данных параметров.

.Чтобы определить режим и тип маршрутизации этапа:
. В поле _Режим_ укажите предпочтительный режим согласования:
+
* _Согласование_ -- подразумевает рецензирование документов.
* _Подписание_ -- согласование/подписание документов с запросом электронной подписи.
* _Консолидация_ -- работа с версиями файлов, учет правок от согласующих лиц. Формируется одно задание на создание консолидированной (итоговой) версии согласуемого документа.
+
. В поле _Тип маршрутизации_ укажите предпочтительный способ отправки заданий на согласование:
+
* *_Последовательный_* -- участники согласования будут получать задания по очереди, следующий участник получит задание после выполнения задания предыдущим исполнителем.
* *_Параллельный_* -- все участники согласования получат задания одновременно.
* *_Альтернативный_* -- вместо отдельных заданий для каждого согласующего будет сформировано одно задание на всех выбранных согласующих: роль, группу или подразделение. Исполнителем задания становится сотрудник, который первым возьмет задание в работу. У остальных согласующих задание будет удалено.
