= Настройки завершения этапа

При выполнении согласования документа может возникнуть ситуация, когда заданная xref:task-stage-duration.adoc[длительность] этапа уже истекла, а согласования документа не произошло. Чтобы избежать появления "зависших" этапов, используются специальные настройки завершения.

[NOTE]
====
Для исключения "зависших" заданий используются настройки xref:task-auto-complete.adoc[автосогласования].
====

.Чтобы настроить параметры завершения этапа:
. Создайте новую или откройте существующую карточку _Этап согласования_.
. Перейдите на вкладку xref:stage-additional-settings.adoc["Дополнительные настройки"].
. Найдите область _Завершение этапа_
. Чтобы этапы, в которых отсутствуют заданные или xref:route-stage-conditions.adoc[исключенные] из маршрута инициатором согласования исполнители, завершались с определённым вариантом решения, выберите требуемую семантику в поле _Семантика завершения этапа по умолчанию_.
+
Настройка необходима для сохранения целостности маршрута и корректной обработки условий перехода между этапами. По умолчанию для этапов с отсутствующими исполнителями будет использоваться положительная семантика решения.
+
. Чтобы после завершения этапа запускался определённый бизнес-процесс, в поле _По завершении этапа запускать бизнес-процесс_ выберите название требуемого бизнес-процесса.
+
****
Например, после завершения этапа можно запустить бизнес-процесс рассылки уведомлений.

Данный бизнес-процесс будет запущен от имени учетной записи, под которой запущено приложение _wf_ (_Workflow_). Для корректной работы бизнес-процесса в его настройках безопасности должны быть выданы права на чтение для группы _{dv-sys-wf-dir}_.

При старте выбранного произвольного процесса значения переменных будут скопированы из родительского процесса в указанный бизнес-процесс если выполнены следующие условия:

* Созданы переменные того же вида и с таким же названием, как и в xref:ROOT:business-processes.adoc["КС Основной процесс"].
* В дополнительных свойствах этих переменных снят флаг `*Скрыта от родительского процесса*`.

Бизнес-процессы xref:ROOT:business-processes.adoc["КС Последовательное согласование"] и xref:ROOT:business-processes.adoc["КС Параллельное согласование"] будут выполняться независимо от выбранного бизнес-процесса.
****
+
. Чтобы избежать "зависания" согласования при выборе варианта решения с отрицательной семантикой, выберите предпочтительный вариант действий в поле _При первом отказе_:
+
****
* *_Продолжать согласование_* -- согласование по данному этапу будет продолжено. Оставшимся согласующим поступят задания на согласование текущего этапа. Данный вариант настроен по умолчанию.
* *_Завершать этап_* -- действия будут зависеть от xref:stage-mode.adoc[типа маршрутизации], настроенного для этапа:
** _Последовательный_ -- текущий этап будет завершён с отрицательным решением. Оставшимся участникам согласования текущего этапа задания на согласование разосланы не будут. Будет запущен следующий этап согласования в соответствии с маршрутом.
** _Параллельный_ -- текущий этап будет завершён с отрицательным решением. Незавершённые задания остальных участников согласования будут отозваны.
+
На вкладке _Ход согласования_ для данного этапа будут изменены значения строк, соответствующих отозванным заданиям. В столбец _Результат_ будет записано `Отозвано`, в столбец _Комментарий к решению_ записано `Задание отозвано при автоматическом завершении этапа`, в столбец _Дата_ записаны дата и время отзыва задания.
+
* _Завершать согласование_ -- действия будут зависеть от xref:stage-mode.adoc[типа маршрутизации], настроенного для этапа:
** _Последовательный_ -- карточка согласуемого документа будет переведена в состояние `Подготовка`. Оставшимся участникам согласования текущего этапа задания на согласование разосланы не будут.
** _Параллельный_ -- карточка согласуемого документа будет переведена в состояние `Подготовка`. Незавершённые задания остальных участников согласования будут отозваны. На вкладке _Ход согласования_ для данного этапа будут изменены значения строк, соответствующих отозванным заданиям. В столбец _Результат_ будет записано `Отозвано`, в столбец _Комментарий к решению_ записано `Задание отозвано при автоматическом завершении этапа`, в столбец _Дата_ записаны дата и время отзыва задания.
+
Для этапов с типом маршрутизации xref:stage-mode.adoc["Альтернативный"] такая настройка не выполняется, поле _При первом отказе_ неактивно.
****
+
. Сохраните изменения.
