= Скрытие этапа в маршруте согласования

При формировании маршрута согласования, входящие в его состав этапы могут иметь различное назначение. В частности, этапы, предназначенные для каких-либо служебных целей, при подготовке и запуске согласования могут быть скрыты от работающих с документами пользователей.

Скрытие этапов настраивается администратором при создании или редактировании карточки _Этап согласования_. При подключении маршрута согласования в xref:TemplateCard_create.adoc#template[шаблон], в поле *Состав маршрута* администратору будет виден полный список этапов, включая скрытые.

.Чтобы скрыть этап в запущенном согласовании, выполните следующие действия:
. Создайте новую или откройте существующую карточку этапа.
. Перейдите на вкладку *Параметры этапа*.
. Установите флаг в поле *Скрыть этап*.
+
При старте этапа у пользователя в области xref:StageParams_change_stage_before_start.adoc#launch[*Состав маршрута*] скрытые этапы будут отсутствовать. В карточке активного согласования на вкладке xref:StageParams_change_stage_before_start.adoc#active[*Состав маршрута*] скрытые этапы также отображаться не будут.
+
Если этап на момент изменения активен, применение настроек произойдет в последующем цикле.
