[[ariaid-title1]]
== Автоматическое завершение заданий

При работе с заданиями на согласование может возникнуть ситуация, когда заданная xref:StageParams_task_duration.adoc[длительность] задания уже истекла, а согласования документа не произошло. Чтобы избежать появления "зависших" заданий используются настройки автосогласования.

[NOTE]
====
[.note__title]#Прим.:# Для исключения "зависших" этапов используются xref:StageParamsExtra_stage_finish.adoc[настройки завершения этапа].
====

Чтобы настроить автоматическое согласование, выполните следующие действия:

[[task_pw1_25r_4n__steps_jgt_kfr_mm]]
. [.ph .cmd]#Создайте новую или откройте существующую карточку этапа.#
. [.ph .cmd]#Перейдите на вкладку xref:StageParams_task.adoc[Настройки заданий].#
. [.ph .cmd]#Найдите область [.keyword]*Автосогласование* #
. [.ph .cmd]#Чтобы автоматически завершать задания на согласование, длительность которых истекла. установите флаг [.ph .uicontrol]*Автоматически завершать задания по истечении срока исполнения*.#
. [.ph .cmd]#Чтобы задания с истекшей длительностью завершались с определенным вариантом решения, выберите требуемую семантику в поле [.keyword]*Семантика завершения задания*. #
. [.ph .cmd]#Сохраните изменения.#

*На уровень выше:* xref:../pages/StageParams_task.adoc[Настройки заданий]
