[[ariaid-title1]]
== Настройки завершения этапа

При выполнении согласования документа может возникнуть ситуация, когда заданная xref:StageParams_task_duration.adoc[длительность] этапа уже истекла, а согласования документа не произошло. Чтобы избежать появления "зависших" этапов используются специальные настройки завершения.

[NOTE]
====
[.note__title]#Прим.:# Для исключения "зависших" заданий используются настройки xref:StageParams_task_auto_approval.adoc[автосогласования].
====

Чтобы настроить параметры завершения этапа, выполните следующие действия:

. [.ph .cmd]#Создайте новую или откройте существующую карточку [.dfn .term]_Этап согласования_.#
. [.ph .cmd]#Перейдите на вкладку xref:StageParams_extra.adoc[Дополнительные настройки].#
. [.ph .cmd]#Найдите область [.keyword]*Завершение этапа* #
. [.ph .cmd]#Чтобы этапы, в которых отсутствуют заданные исполнители, или xref:Start_conditions.adoc[исключенные] из маршрута инициатором согласования, завершались с определенным вариантом решения, выберите требуемую семантику в поле [.keyword]*Семантика завершения этапа по умолчанию*.#
+
Настройка необходима для сохранения целостности маршрута и корректной обработки условий перехода между этапами. По умолчанию для этапов с отсутствующими исполнителями будет использоваться положительная семантика решения.
. [.ph .cmd]#Чтобы после завершения этапа запускался определенный бизнес-процесс, в поле [.ph .uicontrol]*По завершении этапа запускать бизнес-процесс* выберите название требуемого бизнес-процесса. #
+
Например, после завершения этапа можно запустить бизнес-процесс рассылки уведомлений.
+
Данный бизнес-процесс будет запущен от имени учетной записи, под которой запущено приложение [.dfn .term]_Управление процессами_ ([.dfn .term]_Workflow_). Для корректной работы бизнес-процесса в его настройках безопасности должны быть выданы права на чтение для группы [.keyword]*Системная для WF*.
+
Если для указанного бизнес-процесса создать переменные того же вида и с таким же названием, как и в процессе xref:BusinessProcesses.html[[.keyword]*КС Основной процесс*], а также в дополнительных свойствах этих переменных снять флаг [.ph .uicontrol]*Скрыта от родительского процесса*, то при старте выбранного произвольного процесса значения таких переменных будут скопированы из родительского процесса.
+
Завершение бизнес-процессов link:BusinessProcesses.html[[.keyword]*КС Последовательное согласование*] и link:BusinessProcesses.html[[.keyword]*КС Параллельное согласование *] будет происходить независимо от выбранного бизнес-процесса.
. [.ph .cmd]#Чтобы избежать "зависания" согласования при выборе варианта решения с отрицательной семантикой, выберите предпочтительный вариант действий в поле [.keyword]*При первом отказе*:   #
* [.keyword .parmname]_Продолжать согласование_ - согласование по данному этапу будет продолжено, оставшимся согласующим поступят задания на согласование текущего этапа; данный вариант настроен по умолчанию;
* [.keyword .parmname]_Завершать этап_ - действия будут зависеть от link:StageParams_common_mode.adoc[типа маршрутизации], настроенного для этапа:
** [.keyword]*Последовательный* - текущий этап будет завершен с отрицательным решением, оставшимся участникам согласования текущего этапа задания на согласование разосланы не будут; будет выполнен старт следующего этапа согласования в соответствии с маршрутом;
** [.keyword]*Параллельный* - текущий этап будет завершен с отрицательным решением; незавершенные задания остальных участников согласования будут отозваны; на вкладке [.keyword]*Ход согласования* для данного этапа будут изменены значения строк, соответствующих отозванным заданиям (в столбец [.keyword]*Результат* будет записано `Отозвано`, в столбец [.keyword]*Комментарий к решению* записано`                                     Задание отозвано при автоматическом завершении                                     этапа`, в столбец [.keyword]*Дата* записаны дата и время отзыва задания).
* [.keyword .parmname]_Завершать согласование_ - действия будут зависеть от xref:StageParams_common_mode.adoc[типа маршрутизации], настроенного для этапа:
** [.keyword]*Последовательный* - карточка согласуемого документа будет переведена в состояние `Подготовка`; оставшимся участникам согласования текущего этапа задания на согласование разосланы не будут;
** [.keyword]*Параллельный* - карточка согласуемого документа будет переведена в состояние `Подготовка`; незавершенные задания остальных участников согласования будут отозваны; на вкладке [.keyword]*Ход согласования* для данного этапа будут изменены значения строк, соответствующих отозванным заданиям (в столбец [.keyword]*Результат* будет записано `Отозвано`, в столбец [.keyword]*Комментарий к решению* записано`                                     Задание отозвано при автоматическом завершении                                     этапа`, в столбец [.keyword]*Дата* записаны дата и время отзыва задания);
+
Для этапов с типом маршрутизации xref:StageParams_common_mode.html[[.keyword .parmname]_Альтернативный_] такая настройка не выполняется, поле [.keyword]*При первом отказе* неактивно.
. [.ph .cmd]#Сохраните изменения.#

*На уровень выше:* link:../pages/StageParams_extra.adoc[Дополнительные настройки]
