[[ariaid-title1]]
== Варианты решений

Модуль [.dfn .term]_Конструктор согласований_ позволяет определить для каждого из этапов согласования набор доступных решений, которые могут принимать участники согласования. Под решениями подразумеваются варианты завершения задания, доступные пользователям в виде кнопок на ленте карточки задания согласующего.

[NOTE]
====
[.note__title]#Внимание:# В поставляемом решении для видов карточек [.keyword .parmname]_Задание КС - На согласование_, [.keyword .parmname]_Задание КС - На подписание_ и [.keyword .parmname]_Задание КС - На консолидацию_ на ленте карточек будут отсутствовать кнопки принятия решений. Предполагается, что настройка данных кнопок будет выполнена администратором.
====

Решение состоит из следующих частей:

* название решения (например, «Согласовать с замечаниями», «Отклонить» и т.д.);
* семантика (трактовка решения в системе, например: решение «Согласовать» обрабатывать как «Положительное», а «Согласовать с замечаниями» - как «Условно-положительное»).

В первой версии предусмотрены следующие варианты семантики решения:

* [.keyword]*Положительное* (например, «Согласовать», «Утвердить»);
* [.keyword]*Условно-положительное* (например, «Согласовать с замечаниями»);
* [.keyword]*Отрицательное* (например, «Не утвердить», «Отказать»);
* [.keyword]*Новый цикл* – запуск нового цикла согласования (повторный старт маршрута);
* [.keyword]*Добавление согласующих* - возможность добавить новых согласующих в цикл согласования;
* [.keyword]*Отмена* – отмена текущего согласования с отзывом всех заданий (например, «Вернуть на подготовку»);
* [.keyword]*Завершение* – окончание процесса согласования, документ прошел все этапы процесса – согласован, подписан, зарегистрирован и т.д. (Например, «Зарегистрировать»).

Результат выполнения этапа и маршрута рассчитывается в зависимости от принятых решений по определенным xref:Approving_finish.adoc[правилам].

Чтобы определить варианты принимаемых решений, выполните следующие действия:

[[task_sxr_3fr_mm__steps_jgt_kfr_mm]]
. [.ph .cmd]#Создайте новую или откройте существующую карточку этапа.#
. [.ph .cmd]#Перейдите на вкладку xref:StageParams_task.adoc[Настройки заданий].#
. [.ph .cmd]#В поле [.keyword]*Варианты решений* настройте решения:#
* xref:StageParams_task_decisions_add.adoc[Добавьте вариант решения];
* xref:StageParams_task_decisions_change.adoc[Измените вариант решения];
* xref:StageParams_task_decisions_delete.adoc[Удалите вариант решения];
* xref:StageParams_task_decisions_move.adoc[Переместите вариант решения].

* *xref:../pages/StageParams_task_decisions_add.adoc[Добавление решения]* +
* *xref:../pages/StageParams_task_decisions_change.adoc[Изменение варианта решения]* +
* *xref:../pages/StageParams_task_decisions_delete.adoc[Удаление варианта решения]* +
* *xref:../pages/StageParams_task_decisions_move.adoc[Изменение порядка отображения решений в карточке]* +

*На уровень выше:* xref:../pages/StageParams_task.adoc[Настройки заданий]
