[[ariaid-title1]]
== Скрытие этапа в маршруте согласования

При формировании маршрута согласования, входящие в его состав этапы могут иметь различное назначение. В частности, этапы, предназначенные для каких-либо служебных целей, при подготовке и запуске согласования могут быть скрыты от работающих с документами пользователей.

Скрытие этапов настраивается администратором при создании или редактировании карточки [.dfn .term]_Этап согласования_. При подключении маршрута согласования в xref:TemplateCard_create.html#task_ixh_nly_4m__image_qhx_vnw_lm[шаблон], в поле [.keyword]*Состав маршрута* администратору будет виден полный список этапов, включая скрытые.

Чтобы скрыть этап в запущенном согласовании, выполните следующие действия:

. [.ph .cmd]#Создайте новую или откройте существующую карточку этапа.#
. [.ph .cmd]#Перейдите на вкладку [.keyword]*Параметры этапа*.#
. [.ph .cmd]#Установите флаг в поле [.ph .uicontrol]*Скрыть этап*.#
+
При старте этапа у пользователя в области link:StageParams_change_stage_before_start.html#task_kgx_wnk_4n__image_cvm_phf_pn[[.keyword]*Состав маршрута*] скрытые этапы будут отсутствовать. В карточке активного согласования на вкладке link:StageParams_change_stage_before_start.html#task_kgx_wnk_4n__image_hz4_2yf_pn[[.keyword]*Состав маршрута*] скрытые этапы также отображаться не будут.

Если этап на момент изменения активен, применение настроек произойдет в последующем цикле.

*На уровень выше:* link:../pages/StageParams.adoc[Параметры этапа]
