= Длительность

Длительность выполнения может задаваться как для всего этапа, так и для отдельного задания.

Если длительность задается для этапа, при последовательной маршрутизации заданий длительность этапа поделится ровно между всеми участниками, а при параллельной будет равняться длительности отдельного задания. Для заданий задается длительность исполнения отдельного задания.

Допускается задание длительности выполнения как для первого прохождения этапа, так и для повторного его прохождения. Данная настройка может быть удобна для случаев, когда по окончании первого цикла согласовать документ не удалось. В этом случае, при старте нового цикла и всех последующих стартах будет использоваться другое значение длительности.

.Чтобы задать длительность этапа, выполните следующие действия:
. Создайте новую или откройте существующую карточку этапа.
. Перейдите на вкладку xref:StageParams_task.adoc[Настройки заданий].
. Выберите предпочтительный вариант настройки длительности при помощи выбора нужной опции:
* *Длительность для задания*;
* *Длительность для этапа*.
. В поле *Длительность (часы)* укажите время в часах, в течение которого должно быть выполнено задание/этап. Длительность вычисляется согласно xref:StageParams_task_calendar.adoc[бизнес-календарю].
. Если требуется указать длительность выполнения этапа при последующих проходах, установите флаг в поле *В следующих циклах* и в соседнем поле укажите количество выделенных часов.

Настроенная длительность будет отображаться в *Карте этапов* карточки _Маршрут согласования_.

Чтобы исключить появление заданий с истекшей длительностью, рекомендуется настроить xref:StageParams_task_auto_approval.adoc[Автоматическое завершение заданий].
