= Варианты решений

Модуль _Конструктор согласований_ позволяет определить для каждого из этапов согласования набор доступных решений, которые могут принимать участники согласования. Под решениями подразумеваются варианты завершения задания, доступные пользователям в виде кнопок на ленте карточки задания согласующего.

[CAUTION]
====
В поставляемом решении для видов карточек _Задание КС - На согласование_, _Задание КС - На подписание_ и _Задание КС - На консолидацию_ на ленте карточек будут отсутствовать кнопки принятия решений. Предполагается, что настройка данных кнопок будет выполнена администратором.
====

.Решение состоит из следующих частей:
* название решения (например, "Согласовать с замечаниями", "Отклонить" и т.д.);
* семантика (трактовка решения в системе, например: решение "Согласовать" обрабатывать как "Положительное", а "Согласовать с замечаниями" - как "Условно-положительное").

.В первой версии предусмотрены следующие варианты семантики решения:
* *Положительное* (например, "Согласовать", "Утвердить");
* *Условно-положительное* (например, "Согласовать с замечаниями");
* *Отрицательное* (например, "Не утвердить", "Отказать");
* *Новый цикл* – запуск нового цикла согласования (повторный старт маршрута);
* *Добавление согласующих* - возможность добавить новых согласующих в цикл согласования;
* *Отмена* – отмена текущего согласования с отзывом всех заданий (например, "Вернуть на подготовку");
* *Завершение* – окончание процесса согласования, документ прошел все этапы процесса – согласован, подписан, зарегистрирован и т.д. (Например, "Зарегистрировать").

Результат выполнения этапа и маршрута рассчитывается в зависимости от принятых решений по определенным xref:Approving_finish.adoc[правилам].

.Чтобы определить варианты принимаемых решений, выполните следующие действия:
. Создайте новую или откройте существующую карточку этапа.
. Перейдите на вкладку xref:StageParams_task.adoc[Настройки заданий].
. В поле *Варианты решений* настройте решения:
* xref:StageParams_task_decisions_add.adoc[Добавьте вариант решения];
* xref:StageParams_task_decisions_change.adoc[Измените вариант решения];
* xref:StageParams_task_decisions_delete.adoc[Удалите вариант решения];
* xref:StageParams_task_decisions_move.adoc[Переместите вариант решения].
