= Автоматическое завершение заданий

При работе с заданиями на согласование может возникнуть ситуация, когда заданная xref:StageParams_task_duration.adoc[длительность] задания уже истекла, а согласования документа не произошло. Чтобы избежать появления "зависших" заданий используются настройки автосогласования.

[NOTE]
====
Для исключения "зависших" этапов используются xref:StageParamsExtra_stage_finish.adoc[настройки завершения этапа].
====

.Чтобы настроить автоматическое согласование, выполните следующие действия:
. Создайте новую или откройте существующую карточку этапа.
. Перейдите на вкладку xref:StageParams_task.adoc[Настройки заданий].
. Найдите область *Автосогласование*
. Чтобы автоматически завершать задания на согласование, длительность которых истекла. установите флаг *Автоматически завершать задания по истечении срока исполнения*.
. Чтобы задания с истекшей длительностью завершались с определенным вариантом решения, выберите требуемую семантику в поле *Семантика завершения задания*.
. Сохраните изменения.
