[[ariaid-title1]]
== Название

Для заданий, которые будут отправляться исполнителям в рамках конкретного этапа, можно указать определенное название. Данное название будет отображаться в заголовке окон полученных заданий наряду с указанием режима. Например, если указать название «Проект нового здания» для выбранного режима [.keyword .parmname]_Подписание_ в заголовке окна задания, созданное для вида документа [.keyword .parmname]_Исходящий_ будет отображаться текст: `Подписание: Исходящий Проект нового                     здания`.

Если поле [.keyword]*Название* не заполнено, название задания будет сформировано как: [.keyword]*<Название режима>: <Название согласуемого документа> - Задание*.

Чтобы указать название, которое будет отображаться в заголовках окон исполнителей заданий данного этапа, выполните следующие действия:

[[task_snh_k2k_4n__steps_vb1_r2k_4n]]
. [.ph .cmd]#Создайте новую или откройте существующую карточку этапа.#
. [.ph .cmd]#Перейдите на вкладку xref:StageParams_task.adoc[Настройки заданий].#
. [.ph .cmd]#В поле [.keyword]*Название* укажите название для заданий.#
+
Поле не обязательно для заполнения.

*Parent topic:* xref:../pages/StageParams_task.adoc[Настройки заданий]
