[[ariaid-title1]]
== Режим и Тип маршрутизации

Параметры [.keyword]*Режим* и [.keyword]*Тип маршрутизации* обязательно должны быть заполнены при настройке этапа. [.keyword]*Режим* отображается в названии заданий и определяет выбор сценария работы заданий. Параметр [.keyword]*Тип маршрутизации* определяет способ рассылки заданий участникам согласования на данном этапе. При настройке возможны любые комбинации использования данных параметров.

Чтобы определить режим и тип маршрутизации этапа, выполните следующие действия:

. [.ph .cmd]#В поле [.keyword]*Режим* укажите предпочтительный режим согласования: #
* [.keyword .parmname]_Согласование_ - подразумевает рецензирование документов;
* [.keyword .parmname]_Подписание_ - согласование/подписание документов с запросом электронно-цифровой подписи;
* [.keyword .parmname]_Консолидация_ - работа с версиями файлов, учет правок от согласующих лиц. Формируется одно задание на создание консолидированной (итоговой) версии согласуемого документа.
. [.ph .cmd]#В поле [.keyword]*Тип маршрутизации* укажите предпочтительный способ отправки заданий на согласование: #
* [.keyword .parmname]_Последовательный_ - участники согласования будут получать задания по очереди, следующий участник получит задание после выполнения задания предыдущим исполнителем;
* [.keyword .parmname]_Параллельный_ - все участники согласования получат задания одновременно;
* [.keyword .parmname]_Альтернативный_ - вместо отдельных заданий для каждого согласующего будет сформировано одно задание на всех выбранных согласующих (роль/группу/подразделение). Исполнителем задания становится сотрудник, который первым возьмет задание в работу. У остальных согласующих задание будет удалено.

*На уровень выше:* xref:../pages/StageParams.adoc[Параметры этапа]
