[[ariaid-title1]]
== Виды карточек

Модуль «Конструктор согласований» добавляет в [.dfn .term]_Справочник видов карточек_ виды карточек, перечисленные далее.

. [.dfn .term]_Согласование КС_ – вид карточек, предназначенных для инициирования и выполнения согласований, настроенных в Модуле. Связан с карточкой [.dfn .term]_Маршрут согласования_, хранит в себе ход согласования, историю, файлы и версии, добавленные участниками согласования, также содержит элементы управления согласованием.
. [.dfn .term]_Задание КС_ с подвидами ([.dfn .term]_На согласование_, [.dfn .term]_На подписание_, [.dfn .term]_На консолидацию_) – вид карточек, отправляемых участникам согласования. Карточки предоставляют пользователю возможность работы с основными файлами (просмотр, создание версий, комментирование и т.д.), просмотра дополнительных файлов. В ходе всего процесса работы с заданием участник согласования может ввести комментарий/файл комментария.

*На уровень выше:* xref:../pages/Structureof_program.adoc[Структура Модуля]
