= Длительность

Длительность выполнения может задаваться как для всего этапа, так и для отдельного задания.

.Если длительность задаётся для этапа:
* При последовательной маршрутизации заданий длительность этапа поделится ровно между всеми участниками,
* При параллельной маршрутизации длительность будет равняться длительности отдельного задания.
* Для заданий задаётся длительность исполнения отдельного задания.

Допускается задание длительности выполнения как для первого прохождения этапа, так и для повторного его прохождения. Данная настройка может быть удобна, когда по окончании первого цикла согласовать документ не удалось. Тогда при старте нового цикла и всех последующих стартах будет использоваться другое значение длительности.

.Чтобы задать длительность этапа:
. Создайте новую или откройте существующую карточку этапа.
. Перейдите на вкладку xref:stage-task.adoc[Настройки заданий].
. Выберите предпочтительный вариант настройки длительности:
+
* *Длительность для задания*.
* *Длительность для этапа*.
+
. В поле _Длительность (часы)_ укажите время в часах, в течение которого должно быть выполнено задание/этап. Длительность вычисляется согласно xref:task-business-calendar.adoc[бизнес-календарю].
. Если требуется указать длительность выполнения этапа при последующих проходах, установите флаг `*В следующих циклах*` и в соседнем поле укажите количество выделенных часов.
+
Настроенная длительность будет отображаться в _Карте этапов_ карточки _Маршрут согласования_.

Чтобы исключить появление заданий с истекшей длительностью, рекомендуется настроить xref:task-auto-complete.adoc[Автоматическое завершение заданий].
