= Варианты решений

Модуль _{ad}_ позволяет определить для каждого из этапов согласования набор доступных решений, которые могут принимать участники согласования. Под решениями подразумеваются варианты завершения задания, доступные пользователям в виде кнопок на ленте карточки задания согласующего.

[CAUTION]
====
В поставляемом решении для видов карточек _Задание КС -- На согласование_, _Задание КС -- На подписание_ и _Задание КС -- На консолидацию_ на ленте карточек будут отсутствовать кнопки принятия решений. Предполагается, что настройка данных кнопок будет выполнена администратором.
====

.Решение состоит из следующих частей:
* Название решения, например *Согласовать с замечаниями*, *Отклонить* и другие.
* Семантика -- трактовка решения в системе, например решение *_Согласовать_* обрабатывать как _Положительное_, а *_Согласовать с замечаниями_* -- как _Условно-положительное_).

.В первой версии предусмотрены следующие варианты семантики решения:
* _Положительное_: *_Согласовать_*, *_Утвердить_*.
* _Условно-положительное_: *_Согласовать с замечаниями_*.
* _Отрицательное_: *_Не утвердить_*, *_Отказать_*.
* _Новый цикл_ -- запуск нового цикла согласования (повторный старт маршрута).
* *_Добавление согласующих_* -- возможность добавить новых согласующих в цикл согласования.
* _Отмена_ -- отмена текущего согласования с отзывом всех заданий, например, *_Вернуть на подготовку_*.
* _Завершение_ -- окончание процесса согласования, когда документ прошел все этапы процесса -- _Согласован_, _Подписан_, _Зарегистрирован_ и прочие. Например, *_Зарегистрировать_*.

Результат выполнения этапа и маршрута рассчитывается в зависимости от принятых решений по определенным xref:Approving_finish.adoc[правилам].

.Чтобы определить варианты принимаемых решений:
. Создайте новую или откройте существующую карточку этапа.
. Перейдите на вкладку xref:stage-task.adoc[Настройки заданий].
. В поле *Варианты решений* настройте решения:
* xref:StageParams_task_decisions_add.adoc[Добавьте вариант решения];
* xref:StageParams_task_decisions_change.adoc[Измените вариант решения];
* xref:StageParams_task_decisions_delete.adoc[Удалите вариант решения];
* xref:StageParams_task_decisions_move.adoc[Переместите вариант решения].
