= Варианты решений

Модуль _{ad}_ позволяет определить для каждого из этапов согласования набор доступных решений, которые могут принимать участники согласования. Под решениями подразумеваются варианты завершения задания, доступные пользователям в виде кнопок на ленте карточки задания согласующего.

[CAUTION]
====
В поставляемом решении для видов карточек _Задание КС -- На согласование_, _Задание КС -- На подписание_ и _Задание КС -- На консолидацию_ на ленте карточек будут отсутствовать кнопки принятия решений. Предполагается, что настройка данных кнопок будет выполнена администратором.
====

.Решение состоит из следующих частей:
* Название решения, например *Согласовать с замечаниями*, *Отклонить* и другие.
* Семантика -- трактовка решения в системе, например решение *_Согласовать_* обрабатывать как _Положительное_, а *_Согласовать с замечаниями_* -- как _Условно-положительное_).

.В первой версии предусмотрены следующие варианты семантики решения:
include::partial$excerpts.adoc[tags=decisions]

Результат выполнения этапа и маршрута рассчитывается в зависимости от принятых решений по определённым xref:approval-finish-rules.adoc[правилам].

.Чтобы определить варианты принимаемых решений:
. Создайте новую или откройте существующую карточку этапа.
. Перейдите на вкладку xref:stage-task.adoc[Настройки заданий].
. В поле _Варианты решений_ настройте решения:
* xref:task-decision-add.adoc[Добавьте вариант решения].
* xref:task-decision-change.adoc[Измените вариант решения].
* xref:task-decision-remove.adoc[Удалите вариант решения].
* xref:task-decision-order.adoc[Переместите вариант решения].
