[[ariaid-title1]]
== Принудительное завершение согласования

Согласование документа может быть завершено [.keyword]*Инициатором* согласования на любом этапе выполнения. Данная операция используется для принудительного перевода документа в состояние `Согласован` или `Подписан` с сохранением результатов текущего согласования, при отсутствии отрицательных решений по согласованию.

Чтобы завершить согласование, выполните следующие действия:

[[task_nyd_nzd_pm__steps_zw4_syj_yj]]
. [.ph .cmd]#xref:Approval_open_active_approval.adoc[Откройте] активное согласование.#
. [.ph .cmd]#Нажмите на ленте инструментов карточки кнопку [.ph .uicontrol]*Завершить*.#
+
Будут отозваны незавершенные задания исполнителей. Результаты на вкладке [.keyword]*Лист согласования* карточки [.dfn .term]_Документ_ не будут удалены, задания оставшимся согласующим не будут созданы. Вне зависимости от наличия отрицательных решений по согласованию, документ перейдет в итоговое состояние, указанное в карточке [.dfn .term]_Маршрут согласования_ (`Согласован` или `Подписан`, в зависимости от режима согласования и вида документа).

*На уровень выше:* xref:../pages/Monitoring.adoc[Мониторинг и управление ходом согласования]
