[[ariaid-title1]]
== Принудительное прекращение текущего этапа

У [.keyword]*Инициатора* согласования имеется возможность завершения текущего этапа согласования во время его исполнения. Завершить можно как один, так и несколько этапов, если в настройках маршрута был предусмотрен одновременный старт сразу нескольких этапов.

[NOTE]
====
[.note__title]#Прим.:# Для команды используется специализированная операция редактирования [.keyword]*Прекратить текущий этап*.
====

Чтобы прекратить текущий этап согласования, выполните следующие действия:

. [.ph .cmd]#xref:Approval_open_active_approval.adoc[Откройте] активное согласование.#
. [.ph .cmd]#Нажмите на ленте инструментов карточки кнопку [.ph .uicontrol]*Прекратить текущий этап*.#
+
Появится сообщение: `Текущий этап согласования будет                         прекращён, все отправленные незавершенные задания – отозваны. Согласование                         перейдет на следующий этап в соответствии с маршрутом.                         Продолжить?`.
. [.ph .cmd]#Чтобы завершить этап, нажмите [.ph .uicontrol]*Продолжить*. #
+
Для завершенного этапа будет установлена отрицательная семантика, все незавершенные задания участников согласования будут отозваны. В согласовании будет выполнен старт следующего этапа в соответствии с маршрутом.

На вкладке xref:Approval_view_approval_list.html[[.keyword]*Ход согласования*] будут удалены строки, соответствующие согласующим, от которых ожидалось решение. Те решения, которые были приняты до момента прекращения этапа, останутся как на вкладке [.keyword]*Ход согласования*, так и [.keyword]*Листе согласования*.

*На уровень выше:* link:../pages/Monitoring.adoc[Мониторинг и управление ходом согласования]
