= Принудительное прекращение текущего этапа

У _Инициатора_ согласования имеется возможность завершения текущего этапа согласования во время его исполнения. Завершить можно как один, так и несколько этапов, если в настройках маршрута был предусмотрен одновременный старт сразу нескольких этапов.

[NOTE]
====
Для команды используется специализированная операция редактирования *Прекратить текущий этап*.
====

.Чтобы прекратить текущий этап согласования:
. xref:approval-active-open.adoc[Откройте] активное согласование.
. Нажмите на ленте инструментов карточки кнопку *Прекратить текущий этап*.
+
Появится сообщение: `Текущий этап согласования будет прекращён, все отправленные незавершенные задания -- отозваны. Согласование перейдет на следующий этап в соответствии с маршрутом. Продолжить?`.
+
. Чтобы завершить этап, нажмите *Продолжить*.
+
Для завершенного этапа будет установлена отрицательная семантика, все незавершенные задания участников согласования будут отозваны. В согласовании будет выполнен старт следующего этапа в соответствии с маршрутом.
+
На вкладке xref:approval-view-list.adoc[_Ход согласования_] будут удалены строки, соответствующие согласующим, от которых ожидалось решение. Те решения, которые были приняты до момента прекращения этапа, останутся как на вкладке _Ход согласования_, так и *Листе согласования*.
