= Мониторинг и управление ходом согласования

Мониторинг режимов согласования модуля _{ad}_ выполняется средствами приложения _{dv} 5. {dm}_.

Мониторинг хода согласования может производиться _Инициатором_ согласования и _Консолидатором_ несколькими способами:

Мониторинг документов на согласовании::
Выполняется в папке menu:Мои документы[Я автор]. В папке отображаются все документы все документы в состояниях `Подготовка`, `Согласование` или `Подписание`. Документы в представлении сгруппированы по состоянию, отображается состояние активного согласования.

Просмотр Листа согласования в карточке Документ::
Таблица в карточке документа. Отображаются список сотрудников, которые должны согласовать документ, а также окончательный результат всех согласований.

Просмотр журнала согласования::
Чтобы открыть журнал, необходимо воспользоваться одноименной кнопкой в карточке _Документ_. При этом будет открыто окно, в котором будут показаны все карточки _Согласование_, созданные из данной карточки _Документ_. Из _Журнала согласования_ любую карточку согласования можно открыть для анализа.

Просмотр активного согласования::
Чтобы открыть карточку активного согласования, необходимо в карточке _Документ_ нажать на кнопку *Открыть согласование*.

Управление активным согласованием::
Все операции выполняются в карточке активного согласования при помощи кнопок, расположенных на ленте инструментов карточки:
* *Остановить* -- временная остановка согласования.
* *Запустить* -- повторный запуск приостановленного согласования.
* *Отменить* -- принудительная остановка согласования.
* *Завершить* -- принудительное завершение согласования.
* *Прекратить текущий этап* -- принудительное завершение текущего этапа согласования.
* *Открыть Консоль управления* -- xref:winclient:admin:open-msg.adoc[открыть карточку сообщения].
+
[NOTE]
====
Пользователи с ролью _{dv-ad-admins-dir}_ могут дополнительно просматривать карточку бизнес-процесса.
====
