= Варианты решений по заданиям

В полученных заданиях на согласование и консолидацию пользователям на ленте карточек пользователям будут доступны кнопки для завершения заданий. Данные кнопки настраиваются администратором и могут различаться для разных видов карточек.

В данной версии модуля {ad} предусмотрены следующие xref:approval-decisions.adoc[варианты решений], которые могут быть приняты согласующими:

Положительное::
Например, *Согласовать*, *Подписать*, *Утвердить*. При выборе данного варианта задание будет завершено.

Условно-положительное::
Например, *Согласовать с замечаниями*, *Подписать с комментарием*. При выборе данного варианта у пользователя появится окно ввода текстового комментария. После ввода комментария задание будет завершено.

Отрицательное::
Например, *Не утвердить*, *Не согласовано*, *Отказать*. При выборе данного варианта у пользователя появится окно для ввода текстового комментария. После ввода комментария задание будет завершено.

Новый цикл::
Например, *Повторить согласование*. При выборе данного варианта у пользователя появится окно для ввода текстового комментария. После ввода комментария будет запущен новый цикл согласования.

Добавление согласующих::
Например, *Дополнительное согласование*. При выборе данного варианта у пользователя появится окно для ввода текстового комментария и указания дополнительных согласующих.
+
После выбора дополнительных согласующих, в зависимости от настроек, данным сотрудникам будет отправлено задание на согласование, либо предварительно будет отправлено задание инициатору для утверждения новых участников.

Отмена::
Например, *Отменить согласование*. При выборе данного варианта у пользователя появится окно для ввода текстового комментария. После ввода комментария согласование будет отменено.

Завершение::
Например, *Зарегистрировать*. При выборе данного варианта процесс согласования будет принудительно завершен.

Вернуть на предыдущий этап::
+
[WARNING]
====
Только для xref:admin:route-advanced.adoc[усовершенствованного согласования]!
====
+
Позволяет вернуть согласование на предыдущий этап, чтобы повторить его в текущем цикле. При возвращении на предыдущий этап будет предложено ввести комментарий (можно пропустить).
