[[ariaid-title1]]
== Работа с комментариями при согласовании

При выполнении согласований предусмотрены следующие виды комментариев, которые могут быть добавлены согласующими:

xref:File_comment_add.adoc[Комментарий к версии]::
  Комментарий добавляется исполнителем задания на согласование при помощи контекстного меню, вызываемого в области [.keyword]*Версии и комментарии*. В этой же области пользователям доступен просмотр как собственных комментариев, так и комментариев других пользователей.
  +
  Комментарий будет отображаться в области [.keyword]*Комментарии* у [.keyword]*Инициатора* согласования при открытии активного согласования.
xref:Comments_decision_add.adoc[Комментарий к решению]::
  Комментарий добавляется исполнителем задания на согласование при принятии условно-положительного или отрицательного решения по согласованию. Просмотр комментария будет доступен остальным участниками согласования в области [.keyword]*Комментарии к решению* заданий на согласование.
xref:Discussion.adoc[Комментарий к обсуждению]::
  Комментарий добавляется любым согласующим по ходу выполнения согласования на вкладке [.keyword]*Обсуждение*. Просмотр комментария доступен остальным участникам согласования на этой же вкладке.

* *xref:../pages/Comments_decision_add.adoc[Формирование комментария к решению]* +

*На уровень выше:* xref:../pages/Approving.adoc[Согласование и рецензирование документа]
