= Работа с комментариями при согласовании

При выполнении согласований предусмотрены следующие виды комментариев, которые могут быть добавлены согласующими:

xref:File_comment_add.adoc[Комментарий к версии]::
Комментарий добавляется исполнителем задания на согласование при помощи контекстного меню, вызываемого в области _Версии и комментарии_. В этой же области пользователям доступен просмотр как собственных комментариев, так и комментариев других пользователей.
+
Комментарий будет отображаться в области *Комментарии* у _Инициатора_ согласования при открытии активного согласования.

xref:Comments_decision_add.adoc[Комментарий к решению]::
Комментарий добавляется исполнителем задания на согласование при принятии условно-положительного или отрицательного решения по согласованию. Просмотр комментария будет доступен остальным участниками согласования в области *Комментарии к решению* заданий на согласование.

xref:Discussion.adoc[Комментарий к обсуждению]::
Комментарий добавляется любым согласующим по ходу выполнения согласования на вкладке *Обсуждение*. Просмотр комментария доступен остальным участникам согласования на этой же вкладке.
