[[ariaid-title1]]
== Работа с комментариями при консолидации

При выполнении консолидации предусмотрены два вида комментариев, которые могут быть добавлены [.keyword]*Консолидатором*:

xref:File_comment_add.adoc[Комментарий к версии]::
  Комментарий добавляется при помощи контекстного меню, вызываемого в области [.keyword]*Файлы для согласования*.
  +
  Комментарий будет отображаться у [.keyword]*Инициатора* согласования при открытии активного согласования и у [.keyword]*Консолидатора* в области [.keyword]*Комментарии* карточки задания.
xref:Approving_make_decision.adoc[Комментарий к решению]::
  Комментарий добавляется при принятии условно-положительного или отрицательного решения по консолидации.
  +
  Просмотр комментария будет доступен остальным участниками согласования в области [.keyword]*Комментарии* заданий на согласование.

Кроме того, консолидатору доступен просмотр комментариев к версиям, добавленных другими участниками согласования.

*На уровень выше:* xref:../pages/Consolidation_files.adoc[Работа с консолидируемыми файлами]
