[[ariaid-title1]]
== Сравнение версий

Для файлов формата MS Word в упрощенном режиме работы с файлами согласующий может выполнить сравнение версий. Сравнение выполняется между выбранной версией текущего этапа и [.keyword .parmname]_Исходной версией_ данного этапа на предыдущем цикле согласования, а также, если согласующий уже принимал участие в согласовании, с версией другого этапа того же цикла.

[NOTE]
====
[.note__title]#ОСТОРОЖНО:# Для файлов формата, отличного от форматов MS Word, сравнение версий не производится.
====

Чтобы сравнить версии, выполните следующие действия:

. [.ph .cmd]#Откройте карточку задания на согласование.#
. [.ph .cmd]#Перейдите на вкладку xref:Approving_files_simple.html[[.keyword]*Файлы для согласования*].#
. [.ph .cmd]#Выберите файл, который требуется сравнить с версией, согласуемой на данном этапе.#
. [.ph .cmd]#Нажмите на кнопку [.keyword]*Показать изменения*.#
+
Команда доступна, если данный согласующий уже принимал участие в согласовании.
+
Будет открыт редактор MS Word в режиме сравнения версий, в котором будет отображен оригинальный документ ([.keyword .parmname]_Исходная версия этапа_) и версия, которая была исходной для этого этапа на прошлом цикле.
. [.ph .cmd]#Сравните версии и закройте документ.#

*На уровень выше:* link:../pages/Approving_files_simple.adoc[Упрощенная работа с файлами на согласовании]
