[[ariaid-title1]]
== Редактирование файла

В упрощенном режиме работы с файлами согласующим может быть отредактирована [.keyword .parmname]_Исходная версия этапа_ или последняя добавленная собственная версия, если файл одного из следующих форматов: .doc, .docm, .docx, .txt, .rtf, .xls, .xlsm, .xlsx, .ppt, .pptx, .vsd, .vsdx. Файлы других форматов открываются только на чтение.

[NOTE]
====
[.note__title]#Прим.:# Если на компьютере, где установлен клиент Docsvision, установлено приложение MS Word, но по умолчанию для текстовых документов форматов *.doc, *.docx, *.rtf выбран другой текстовый редактор, то согласуемые файлы будут открываться в MS Word. Приоритет отдаётся редактору MS Word, т.к. при создании версий и автоконсолидации важен режим рецензирования.
====

Чтобы внести изменения в [.keyword .parmname]_Исходную версию этапа_, выполните следующие действия:

. [.ph .cmd]#Откройте карточку задания на согласование.#
. [.ph .cmd]#Перейдите на вкладку xref:Approving_files_simple.html[[.keyword]*Файлы на согласовании*].#
. [.ph .cmd]#Выберите файл, затем дважды щелкните левой клавишей мыши по его названию.#
+
Файл будет открыт в режиме редактирования. Количество файлов, открываемых одновременно в режиме редактирования, не ограничено. При попытке повторного открытия уже открытого на редактирование файла будет выдано предупреждение: `Файл уже редактируется вами`.

[NOTE]
====
[.note__title]#Важное замечание:# При редактировании файла Microsoft Office, открытого из карточки, следует избегать параллельного открытия файлов с аналогичным именем (из других источников), т.к. это может привести к невозможности сохранения изменений файла в карточку.
====

На вкладке [.keyword]*Версии и комментарии* будет автоматически создана новая версия файла. Именно она в упрощенном режиме будет открыта у пользователя в режиме link:File_simple_change.adoc[редактирования]. Если выбран файл формата MS Word, в документе будет включен режим исправлений.

Если используется тип маршрутизации [.keyword .parmname]_Параллельный_ или [.keyword .parmname]_Альтернативный_, новая версия файла будет создана на основе xref:Approving_files.html[[.keyword .parmname]_Исходной версии этапа_]. Для типа маршрутизации [.keyword .parmname]_Последовательный_ версия будет создана на основе версии предыдущего участника (только для первого участника - на основе [.keyword .parmname]_Исходной версии этапа_).
. [.ph .cmd]#Внесите изменения в файл.#
+
Для файлов формата MS Word изменения будут отображаться в режиме исправлений.
. [.ph .cmd]#Сохраните и закройте файл.#
+
На вкладке [.keyword]*Файлы для согласования* вместо [.keyword .parmname]_Исходной версии этапа_ для просмотра и редактирования станет доступной версия файла с внесенными изменениями. На вкладке [.keyword]*Версии и комментарии* изменения будут сохранены в созданной версии.

*На уровень выше:* link:../pages/Approving_files_simple.adoc[Упрощенная работа с файлами на согласовании]
