= Редактирование файла

В упрощенном режиме работы с файлами согласующим может быть отредактирована _Исходная версия этапа_ или последняя добавленная собственная версия, если файл одного из следующих форматов: .doc, .docm, .docx, .txt, .rtf, .xls, .xlsm, .xlsx, .ppt, .pptx, .vsd, .vsdx. Файлы других форматов открываются только на чтение.

[NOTE]
====
Если на компьютере, где установлен клиент Docsvision, установлено приложение MS Word, но по умолчанию для текстовых документов форматов *.doc, *.docx, *.rtf выбран другой текстовый редактор, то согласуемые файлы будут открываться в MS Word. Приоритет отдаётся редактору MS Word, т.к. при создании версий и автоконсолидации важен режим рецензирования.
====

.Чтобы внести изменения в _Исходную версию этапа_, выполните следующие действия:
. Откройте карточку задания на согласование.
. Перейдите на вкладку xref:Approving_files_simple.adoc[*Файлы на согласовании*].
. Выберите файл, затем дважды щелкните левой клавишей мыши по его названию.
+
Файл будет открыт в режиме редактирования. Количество файлов, открываемых одновременно в режиме редактирования, не ограничено. При попытке повторного открытия уже открытого на редактирование файла будет выдано предупреждение: `Файл уже редактируется вами`.
+
[IMPORTANT]
====
При редактировании файла Microsoft Office, открытого из карточки, следует избегать параллельного открытия файлов с аналогичным именем (из других источников), т.к. это может привести к невозможности сохранения изменений файла в карточку.
====
+
На вкладке *Версии и комментарии* будет автоматически создана новая версия файла. Именно она в упрощенном режиме будет открыта у пользователя в режиме xref:File_simple_change.adoc[редактирования]. Если выбран файл формата MS Word, в документе будет включен режим исправлений.
+
Если используется тип маршрутизации _Параллельный_ или _Альтернативный_, новая версия файла будет создана на основе xref:Approving_files.adoc[_Исходной версии этапа_]. Для типа маршрутизации _Последовательный_ версия будет создана на основе версии предыдущего участника (только для первого участника - на основе _Исходной версии этапа_).
+
. Внесите изменения в файл.
+
Для файлов формата MS Word изменения будут отображаться в режиме исправлений.
+
. Сохраните и закройте файл.
+
На вкладке *Файлы для согласования* вместо _Исходной версии этапа_ для просмотра и редактирования станет доступной версия файла с внесенными изменениями. На вкладке *Версии и комментарии* изменения будут сохранены в созданной версии.
