= Загрузка версии из файла

Загрузка версии предназначена для внесения изменений в файлы различных форматов или для загрузки файла из системы, внешней по отношению _Docsvision_. Загрузить можно как ранее выгруженный файл, так и другой, новый файл. Операция доступна также для исходных версий этапа.

.Чтобы создать новую версию документа или загрузить свою версию из файла, выполните следующие действия:
. Откройте карточку задания на согласование документа.
. На вкладке файла документа правой кнопкой мыши вызовите контекстное меню, затем выберите команду *Загрузить из файла*.
+
Будет открыто стандартное окно для выбора файла из файловой системы.
. Выберите для загрузки файл с тем же именем и расширением, что и выгруженный файл.
+
[NOTE]
====
При работе с файлами MS Office следует учитывать, что в случае сохранения выгруженного файла в новый формат (например, *.docx вместо выгруженного *.doc) загрузка версии файла выполнена не будет.
====
+
На вкладке в дерево версий файла добавится новая версия файла, название которой содержит фамилию сотрудника, внесшего изменения.
