= Сравнение версий

Для файлов формата MS Word в упрощенном режиме работы с файлами согласующий может выполнить сравнение версий. Сравнение выполняется между выбранной версией текущего этапа и _Исходной версией_ данного этапа на предыдущем цикле согласования, а также, если согласующий уже принимал участие в согласовании, с версией другого этапа того же цикла.

[WARNING]
====
Для файлов формата, отличного от форматов MS Word, сравнение версий не производится.
====

.Чтобы сравнить версии:
. Откройте карточку задания на согласование.
. Перейдите на вкладку xref:Approving_files_simple.adoc[_Файлы для согласования_].
. Выберите файл, который требуется сравнить с версией, согласуемой на данном этапе.
. Нажмите на кнопку *Показать изменения*.
+
Команда доступна, если данный согласующий уже принимал участие в согласовании.
+
Будет открыт редактор MS Word в режиме сравнения версий, в котором будет отображен оригинальный документ (_Исходная версия этапа_) и версия, которая была исходной для этого этапа на прошлом цикле.
+
. Сравните версии и закройте документ.
