= Создание и запуск расширенного согласования по документу

Запуск расширенных согласований, созданных средствами модуля _{ad}_, выполняется средствами приложения _{dv} 5. {ud}_. Запуск согласования выполняется из карточки _Документ_ вида _Документ УД_ пользователями с ролью *Автор* и *Регистратор*. Разница состоит только в режиме согласования, который будет выбран пользователем при запуске. Создание режимов согласований, относящихся к модулю _{ad}_, выполняется администратором модуля.

.Согласование предусмотрено:
* для карточки _ДокументУД_, не содержащей вложенных файлов (если данный способ согласования разрешен администратором Модуля);
* для _основных_ файлов, приложенных к карточке.

_Дополнительные_ файлы при проведении согласования не учитываются.

Также в некоторых режимах согласования требуется, чтобы в карточке документа, отправляемого на согласование, были заполнены поле *Согласующие* (для выполнения рецензирования и согласования) и поле *Подписывает* (для выполнения подписания).
