[[ariaid-title1]]
== Создание и запуск расширенного согласования по документу

Запуск расширенных согласований, созданных средствами модуля [.dfn .term]_Конструктор согласований_, выполняется средствами приложения [.dfn .term]_Docsvision 5. Управление документами_. Запуск согласования выполняется из карточки [.dfn .term]_Документ_ вида [.keyword .parmname]_Документ УД_ пользователями с ролью [.keyword]*Автор* и [.keyword]*Регистратор*. Разница состоит только в режиме согласования, который будет выбран пользователем при запуске. Создание режимов согласований, относящихся к модулю [.dfn .term]_Конструктор согласований_, выполняется администратором модуля.

Согласование предусмотрено:

* для карточки [.dfn .term]_ДокументУД_, не содержащей вложенных файлов (если данный способ согласования разрешен администратором Модуля);
* для [.dfn .term]_основных_ файлов, приложенных к карточке.

[.dfn .term]_Дополнительные_ файлы при проведении согласования не учитываются.

Также в некоторых режимах согласования требуется, чтобы в карточке документа, отправляемого на согласование, были заполнены поле [.keyword]*Согласующие* (для выполнения рецензирования и согласования) и поле [.keyword]*Подписывает* (для выполнения подписания).

* *xref:../pages/Approving_start.adoc[Отправка документа на согласование/подписание/консолидацию]* +
* *xref:../pages/Approving_change_stage_params.adoc[Изменение параметров этапа перед отправкой]* +

*На уровень выше:* xref:../pages/Operations.adoc[Описание операций]
