= Мониторинг и управление ходом согласования

Мониторинг режимов согласования модуля _Конструктор согласований_ выполняется средствами приложения _Docsvision 5. Управление документами_.

Мониторинг хода согласования может производиться *Инициатором* согласования и консолидатором несколькими способами:

* *Мониторинг документов на согласовании*. Выполняется в папке `Мои документы / Я автор`. В папке отображаются все документы все документы в состояниях `Подготовка`, `Согласование` или `Подписание`. Документы в представлении сгруппированы по состоянию, отображается состояние активного согласования;
* *Просмотр Листа согласования в карточке Документ* – таблица в карточке документа. Отображаются список сотрудников, которые должны согласовать документ, а также окончательный результат всех согласований;
* *Просмотр журнала согласования* – для открытия журнала необходимо воспользоваться одноименной кнопкой в карточке _Документ_. При этом будет открыто окно, в котором будут показаны все карточки _Согласование_, созданные из данной карточки _Документ_. Из *Журнала согласования* любую карточку согласования можно открыть для анализа.
* *Просмотр активного согласования* – для открытия карточки активного согласования необходимо в карточке _Документ_ нажать на кнопку *Открыть согласование*;
* *Управление активным согласованием* - все операции выполняются в карточке активного согласования при помощи кнопок, расположенных на ленте инструментов карточки:
** *Приостановить согласование* - временная остановка согласования;
** *Запустить приостановленное согласование* - повторный запуск согласования;
** *Отменить согласование* - принудительная остановка согласования;
** *Завершить согласование* - принудительное завершение;
** *Завершить этап согласования* - принудительное завершение текущего этапа.
+
[NOTE]
====
У пользователей с ролью *Администраторы КС* имеется дополнительная возможность открытия карточки бизнес-процесса.
====
