[[ariaid-title1]]
== Мониторинг и управление ходом согласования

Мониторинг режимов согласования модуля [.dfn .term]_Конструктор согласований_ выполняется средствами приложения [.dfn .term]_Docsvision 5. Управление документами_.

Мониторинг хода согласования может производиться [.keyword]*Инициатором* согласования и консолидатором несколькими способами:

* [.keyword]*Мониторинг  документов на согласовании*. Выполняется в папке [.ph .filepath]`Мои документы / Я автор`. В папке отображаются все документы все документы в состояниях `Подготовка`, `Согласование` или `Подписание`. Документы в представлении сгруппированы по состоянию, отображается состояние активного согласования;
* [.keyword]*Просмотр Листа согласования в карточке Документ* – таблица в карточке документа. Отображаются список сотрудников, которые должны согласовать документ, а также окончательный результат всех согласований;
* [.keyword]*Просмотр журнала согласования* – для открытия журнала необходимо воспользоваться одноименной кнопкой в карточке [.dfn .term]_Документ_. При этом будет открыто окно, в котором будут показаны все карточки [.dfn .term]_Согласование_, созданные из данной карточки [.dfn .term]_Документ_. Из [.keyword]*Журнала согласования* любую карточку согласования можно открыть для анализа.   
* [.keyword]*Просмотр активного согласования* – для открытия карточки активного согласования необходимо в карточке [.dfn .term]_Документ_ нажать на кнопку [.ph .uicontrol]*Открыть согласование*;
* [.keyword]*Управление активным согласованием* - все операции выполняются в карточке активного согласования при помощи кнопок, расположенных на ленте инструментов карточки:
** [.keyword]*Приостановить согласование* - временная остановка согласования;
** [.keyword]*Запустить приостановленное согласование* - повторный запуск согласования;
** [.keyword]*Отменить согласование* - принудительная остановка согласования;
** [.keyword]*Завершить согласование* - принудительное завершение;
** [.keyword]*Завершить этап согласования* - принудительное завершение текущего этапа.

[[concept_orw_swd_pm__open_business_prosess]]
[NOTE]
====
[.note__title]#Прим.:# У пользователей с ролью [.keyword]*Администраторы КС* имеется дополнительная возможность открытия карточки бизнес-процесса.
====

* *xref:../pages/Approval_open_active_approval.adoc[Открытие карточки активного согласования Инициатором согласования]* +
* *xref:../pages/Approval_path_consist.adoc[Ознакомление с составом маршрута]* +
* *xref:../pages/Approval_view_approval_list.adoc[Ознакомление с ходом согласования]* +
* *xref:../pages/Approval_postpone_approval.adoc[Остановка и запуск приостановленного согласования]* +
* *xref:../pages/Approval_reject.adoc[Отмена согласования]* +
* *xref:../pages/Approval_finish.adoc[Принудительное завершение согласования]* +
* *xref:../pages/Approval_stage_stop.adoc[Принудительное прекращение текущего этапа]* +

*На уровень выше:* xref:../pages/Operations.adoc[Описание операций]
