[[ariaid-title1]]
== Подписание документа

Режим [.keyword .parmname]_Подписание_ предназначен для сбора решений (согласующих подписей) от участников согласования по итоговой версии документа, сформированной в режиме [.keyword .parmname]_Консолидация_, или последней созданной на этапе согласования версии, если предшествующий текущему этап был последовательным или альтернативным и его режим – согласование.

В данном режиме запрещено создание собственных версий документа. [.keyword]*Участникам* доступна только xref:Approving_files.html[[.keyword .parmname]_Исходная версия этапа_]. После просмотра и ознакомления с данной версией участники подписания принимают решение, которое сопровождается наложением электронно-цифровой подписи.

[NOTE]
====
[.note__title]#Важное замечание:# Запрос на подписание документа в данном режиме может быть отключен администратором модуля.
====

* *link:../pages/Signing_get.adoc[Получение задания и выполнение подписания]* +
* *xref:../pages/Signing_files_simple.adoc[Работа с файлами при подписании]* +

*На уровень выше:* xref:../pages/Operations.adoc[Описание операций]
