[[ariaid-title1]]
== Уровень подготовки пользователя

Для эксплуатации модуля «Конструктор согласований» определены две пользовательские роли: администратор Docsvision и конечный пользователь. На этапе внедрения системы Docsvision в организации появляется дополнительные роли: инженер и программист Docsvision.

Администратор Docsvision устанавливает серверную часть Модуля, выявляет неполадки в работе бизнес-процессов согласования.

Пользователь отправляет документы на согласование и участвует в согласовании документов.

Инженер Docsvision настраивает шаблоны, этапы и маршруты согласования.

Все пользователи Модуля должны обладать базовыми навыками работы на персональном компьютере, в «Windows-клиенте» (модуль «Docsvision 5. Windows-клиент»).

Пользователям необходимо ознакомиться с руководством пользователя модуля «Docsvision 5. Управление документами».

Администратор Docsvision должен обладать навыками настройки модуля «Docsvision 5. Платформа», формирования сертификатов ЭЦП в ОС Windows, использования криптопровайдера «КриптоПро»; а также ознакомиться с документом [.ph]#[.dfn .term]_Модуль «Docsvision 5. Базовые объекты». Руководство администратора_#.

Инженер Docsvision должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение Docsvision.

Программист должен иметь опыт разработки на языке C# или Visual Basic .NET, а также ознакомиться с документом [.ph]#[.dfn .term]_Docsvision 5.5. Руководство программиста_#.

*На уровень выше:* xref:../pages/Introduction.adoc[Введение]
