= Исправленные ошибки

* DV5-2954 (SUP-1301). Этапы в ходе согласования не совпадали с этапами из состава маршрута, если согласование было запущено без показа карточки.
* PCU-760 (SUP-319, SUP-525). Согласующий мог изменить свои версии, созданные им на предыдущих циклах.
* PCU-781 (SUP-319, SUP-525). Было доступно редактирование версий документа в пройденном этапе.
* PCU-810 (SUP-486). В настройке этапов согласования была возможность указать противоречивые настройки (дублирование строк).
* PCU-736 (SUP-167). Была недоступна кнопка просмотра комментария в Ходе согласования.
* DV5-3697 (SUP-1509). Возникала ошибка при указании условия для маршрута согласования.
* PCU-1120 (SUP-1155). Возникала ошибка в БП согласования при добавлении согласующих и делегировании.
* DV5-2608. Исправлен адрес сайта Docsvision в информации о программе в разделе "Установка и удаление программ".
* DV5-2629 (SUP-935). При каждом сохранении карточки "Согласование" обновлялось значение в условии с поисковым словом.
* DV5-2944 (SUP-1814). При обновлении некоторых модулей могли удаляться хранимые процедуры с префиксом "dvbo_".
* DV5-2945 (SUP-1277). Консолидированная версия могла не переносится через этап согласования.
* DV5-2964 (SUP-1311). Работа БП "КС Подпроцесс работы с заданиями" завершался с ошибкой, если согласование было отозвано, но работа функции "Запомнить подчиненные задания" в указанном БП еще не завершалась. Текст ошибки: "Значение переменной `Карточка задания" не задано".
* DV5-2989 (SUP-1321) БП КС Основной процесс завершался с ошибкой на функции "Создание веток дерева". Текст ошибки: "Не удалось выполнить сценарий. Код ошибки: 0. Описание ошибки: File is locked".
* DV5-3008. Экземпляр подпроцесса КС Основной процесс завершался с ошибкой "Объект уже заблокирован текущим пользователем в этой сессии".
* DV5-3068 (SUP-1394). Добавлена версия в пакет установки (MSI).
* DV5-3164. При открытии задания На подписание могла возникнуть ошибка "Версия файла текущего этапа не найдена".
* DV5-3908. В задании На согласование, возвращённом с делегирования, согласующий не видел версию делегата до повторного открытия Windows-клиента.
* DV5-3920, DV5-4237 (SUP-1543). При выборе новой консолидированной версии файла не происходит обновления существующей без сохранения документа в Word.
* DV5-3986 (SUP-1743). При открытии приложенного к карте документа в Word возникала ошибка "Сервер RPC недоступен".
* DV5-3994 (SUP-1757). После редактирования документа по согласования при принятии решения могла возникнуть ошибка "Значение не может быть неопределенным. Имя параметра: session"
* DV5-4045 (SUP-1901). В карточке задания согласования область со списком файлов занимала не всё доступное пространство.
* DV5-4052 (SUP-1884). Не запускался БП, настроенный на смену состояния задания На согласование, если состояние задания изменялось автоматически (автоматическое завершение).
* DV5-4575 (SUP-2440). В листе согласования дата согласования не совпадала с EndDateActual задания согласования.
* DV5-532, PCU-1097 (SUP-989). При использовании функции "Добавить согласующих" в задании согласования дополнительные согласующие не добавлялись, если задание было возвращено на пересогласование от дополнительного согласующего.
* PCU-1157 (SUP-1412). При использовании функции сравнения версии с консолидированной изменялась консолидированная версия.
* SUP-2094. При принятии решения по согласованию могла возникнуть ошибка "Доступ к ликвидированному объекту невозможен. Имя объекта ``VersionsTreePropertyControl""".
* SUP-2184. В работе функции "Создание веток дерева" БП "КС основной процесс" возникала ошибка "Объект уже заблокирован текущим пользователем в этой сессии".
* DV5-2589 (SUP-803). В журнал подписей попадали недействительные подписи.
* DV5-3741 (SUP-2530). У инициатора согласования в карточке согласования отсутствовала кнопка "Прекратить текущий этап", если пользователь не являлся администратором.
* DV5-4229 (SUP-2530). При создании базы данных возникала внутренняя ошибка сервера.
* DV5-2562 (SUP-171). Изменён флаг IsMultipleValued параметра "Буфер пересогласующих" БП "КС Подпроцесс параллельное согласование".
* DV5-3787. В задании согласования без файлов были активны кнопки "Просмотреть" и "Показать изменения".
* DV5-4591. Возникала ошибка при запуске согласование с маршрутом, в котором не было указано поле для получения Автора. Текст ошибки: "Value cannot be null".
* SUP-2602. БП "КС Основной процесс" завершался с ошибкой на функции "Создание веток дерева", если параллельно с созданием файла для нового этапа согласования файл был открыт пользователем для редактирования. Текст ошибки: "Заданное приведение является недопустимым".
* DV5-3709 (SUP-1514). После исполнения задание от дополнительного согласующего возвращалось согласующему, а не его заместителю, который добавил согласующего.
* DV5-3710 (SUP-754). БП "КС Подпроцесс параллельное согласование" завершался с ошибкой после отзыва согласования, если отзыв был выполнен до рассылки заданий исполнителям. Текст ошибки: "Значение переменной `Родительский процесс" не существует".
* DV5-5082 (SUP-2982). При отправке документа на согласование без указания согласующих создавалось множество заданий на согласование, если при запуске этапа была заблокирована карточка документа.
* DV5-5118 (SUP-2984). Исправлена сортировка вариантов завершения задания по согласованию, когда порядок сортировки не установлен.
