= Список изменений в версии

== Функциональные изменения

[#advanced-approval]
Усовершенствованные маршруты согласования::
Добавлена возможность создания и запуска xref:admin:route-advanced.adoc[усовершенствованных] маршрутов согласования. Маршруты, созданные до обновления всё ещё будут работать. Также сохраняется возможность создать новый маршрут со старой логикой.
+
include::admin:partial$excerpts.adoc[tags=manual-delete]

[#task-title]
Заголовок задания::
Теперь в автоматически формируемый заголовок задания добавляется информация о номере цикла и номере прохода (повторения этапа), начиная со вторых номеров, например так:
`Согласование: Документ (цикл 2, проход 3`).
+
Заголовок карточки этапа согласования формируется аналогичным образом.

[#add-approvers]
Добавление согласующих::
Добавлены новые способы xref:admin:stage-approvers.adoc[определения согласующих]. Для усовершенствованного согласования добавлена возможность определить согласующих одновременно несколькими способами, а также возможность xref:admin:stage-approvers.adoc#custom-service[использовать] {service}.

[#version-tree]
Переработано дерево версий::
Работа с версиями согласования в xref:user:approval-simple-mode.adoc[упрощённом] и xref:user:consolidation-version-tree.adoc[обычном] режиме изменена. Подробно работа с версиями описана в соответствующих разделах.

[#compare-final]
Сравнить с итоговой::
Команда этапа консолидации _Сравнить с консолидируемой_ переименована в _Сравнить с итоговой_.

[#comment]
Запрашивать комментарий к решению::
В настройках xref:admin:task-decisions.adoc[вариантов решения] для этапа добавлена возможность обязательно запрашивать комментарий в каждом отдельном решении. Возможность доступна только для усовершенствованного маршрута.

[#start-options]
Изменены условия завершения этапа::
В диалоге xref:admin:stage-finish-settings.adoc[настройки условий завершения] удалены варианты завершения: *_Отмена_*, *_Новый цикл_*, *_Завершение_*. Вместо удалённых добавлены новые: *_Не отрицательное_*, *_Любое_*.
+
* Не отрицательное -- Положительное или Условно-положительное решение.
* Любое -- этап должен быть завершен Положительно, Условно-положительно или Отрицательно.

[#localized-solutions]
Локализация вариантов решения::
Добавлена возможность настроить локализации для xref:admin:task-decisions.adoc[вариантов решения]. Также в локализованном варианте отображается информация о ходе этапа согласования.

[#worker]
Расширение службы {ws}::
Теперь при установке модуля поставляется расширение Службы {ws} для обработки согласований.
+
Компонент доступен для установки только, если xref:workerservice:admin:install.adoc[установлен] модуль "Служба фоновых операций" версии 5.5.2 и выше.

[#delete]
Удаление согласования::
Теперь xref:user:remove-doc-from-approval.adoc[удаление] карточки согласуемого документа приводит к удалению всего согласования полностью.

[#repeat-stage]
Повторение этапов::
Этапы согласования теперь могут повторяться многократно в одном цикле.

//== Изменения в библиотеках карточек
