= Изменения

== Функциональные изменения

[#comment]
Запрашивать комментарий к решению::
В настройках xref:admin:task-decisions.adoc[вариантов решения] для этапа добавлена возможность обязательно запрашивать комментарий в каждом отдельном решении. Возможность доступна только для усовершенствованного маршрута.

[#start-options]
Изменены условия завершения этапа::
В диалоге xref:admin:stage-finish-settings.adoc[настройки условий завершения] удалены варианты завершения: *_Отмена_*, *_Новый цикл_*, *_Завершение_*. Вместо удалённых добавлены новые: *_Не отрицательное_*, *_Любое_*.
+
* Не отрицательное -- Положительное или Условно-положительное решение.
* Любое -- этап должен быть завершен Положительно, Условно-положительно или Отрицательно.

[#localized-solutions]
Локализация вариантов решения::
Добавлена возможность настроить локализации для xref:admin:task-decisions.adoc[вариантов решения]. Также в локализованном варианте отображается информация о ходе этапа согласования.

Расширение службы {ws}::
Теперь при установке модуля поставляется расширение Службы {ws} для обработки согласований.
+
Компонент доступен для установки только, если установлен модуль "{ws}" версии 5.5.2 и выше с xref:workerservice:admin:install.adoc#settings-storage[сервисом настроек].

[#delete]
Удаление согласования::
Теперь xref:user:remove-doc-from-approval.adoc[удаление] карточки согласуемого документа приводит к удалению всего согласования полностью.

[#advanced-approval]
Усовершенствованные маршруты согласования::
Добавлена возможность создания и запуска xref:admin:route-advanced.adoc[усовершенствованных] маршрутов согласования. Маршруты, созданные до обновления всё ещё будут работать. Также сохраняется возможность создать новый маршрут со  старой логикой.

[#repeat-stage]
Повторение этапов::
Этапы согласования теперь могут повторяться многократно в одном цикле.

//== Изменения в библиотеках карточек
