= Ограничения на изменение стандартных настроек модуля

== Ограничения на изменение настроек папок

* Запрещено удалять, перемещать или изменять структуру и настройки папки `{ad}` и её подпапок.

== Ограничения на изменение настроек видов карточек

=== Изменение разметки карточки вида "Задание КС -- На согласование"

==== Изменение разметки карточки вида "Задание КС -- На согласование". Разметки "Подготовка" и "Завершено"

===== Допустимые изменения

Допускается изменение и удаление всех элементов управления.

==== Изменение разметки карточки вида "Задание КС -- На согласование". Разметки "Базовая", "Исполнение" и "Делегирование"

===== Недопустимые изменения

.Запрещена замена на разметочные следующих скриптовых элементов управления:
* Вкладка Задание/Версии и комментарии:
** Дерево версий.
** Вкладки дерева версий.
* Вкладка Задание/Файлы на согласовании:
** Список файлов.

Запрещены любые изменения столбцов в табличных элементах управления: Дополнения, Ход согласования, Комментарии (к версии).

===== Допустимые изменения

Допускается изменение и удаление любых разметочных элементов управления, кроме изменений, указанных в списке недопустимых.

==== Изменение разметки карточки вида "Задание КС -- На консолидацию". Разметки "Подготовка" и "Завершено"

===== Допустимые изменения

Допускается изменение и удаление всех элементов управления.

==== Изменение разметки карточки вида "Задание КС -- На консолидацию". Разметки "Базовая", "Исполнение" и "Делегирование"

===== Недопустимые изменения

.Запрещена замена на разметочные следующих скриптовых элементов управления на вкладке Задание:
* Дерево версий.
* Вкладки дерева версий.

Запрещены любые изменения столбцов в табличных элементах управления: Дополнения, Ход согласования, Комментарии (к версии).

===== Допустимые изменения

Допускается изменение и удаление любых разметочных элементов управления, кроме изменений, указанных в списке недопустимых).

==== Изменение разметки карточки вида "Задание КС -- На подписание". Разметки "Подготовка" и "Завершено"

===== Допустимые изменения

Допускается изменение и удаление всех элементов управления.

==== Изменение разметки карточки вида "Задание КС -- На подписание". Разметки "Базовая", "Исполнение" и "Делегирование"

===== Недопустимые изменения

Запрещена замена на разметочные скриптового элементах управления Список файлов на вкладке Задание.

Запрещены любые изменения столбцов в табличных элементах управления: Дополнения, Ход согласования, Комментарии (к версии).

===== Допустимые изменения

Допускается изменение и удаление любых разметочных элементов управления, кроме изменений, указанных в списке недопустимых).

==== Изменение элемента "HTMLинформация"

В разметках карточек Задание КС для отображения информации о задании используется элемент "HTMLинформация" -- HTML браузер, данные для которого формируются XSLT-преобразованием.

Настройки элемента "HTMLинформация" можно изменять со следующим ограничением: в параметре "XSL преобразование" можно использовать только XSLT-пути, которые уже используются в данном параметре. Если в "XSL преобразовании" нужно обращаться к другим данным (например, полям связанных карточек), необходимо в скрипт карточки задания добавить код, приведённый ниже.

.Показать код
[%collapsible]
====
[source,csharp]
----
using System.Xml;
using System.IO;
....
public virtual void CardActivated(Docsvision.Platform.WinForms.CardActivatedEventArgs e)
{
   SetInformationControlXMLGenerator(); <.>
   this.ApprovalTaskScript.CardActivated(e);
} <.>

private void SetInformationControlXMLGenerator() <.>
{
  var generator === this.ApprovalTaskScript.InformationControlXMLGenerator;
  this.ApprovalTaskScript.InformationControlXMLGenerator === (CardData taskCardData)=>
   {
      string xmlString === generator(taskCardData);
      var doc === new XmlDocument();
      doc.LoadXml(xmlString);

      var items === doc.GetElementsByTagName("CardDocument");
      foreach (XmlNode item in items)
      {
        XmlElement documentElement === (XmlElement)item;
        Guid cardId === Guid.Parse(documentElement.GetAttribute("CardID"));
        var documentCardData === taskCardData.Session.CardManager.GetCardData(cardId, false);

        XmlElement mainInfoElement === (XmlElement)documentElement.SelectSingleNode("MainInfo");
        Guid mainInfoSectionId === new Guid("30eb9b87-822b-4753-9a50-a1825dca1b74");
        string documentName === (string)documentCardData.Sections[mainInfoSectionId].FirstRow.GetString("Name");
        mainInfoElement.SetAttribute("Name", documentName);
      }

      using (var stringWriter === new StringWriter())
      using (var xmlTextWriter === XmlWriter.Create(stringWriter))
      {
          doc.WriteTo(xmlTextWriter);
          xmlTextWriter.Flush();

          return stringWriter.GetStringBuilder().ToString();
      }
  };
}
----
<.> Данный метод будет загружать нестандартные данные.
<.> Данный метод добавляет в переменную `this.ApprovalTaskScript.InformationControlXMLGenerator` узлы,  к которым требуется доступ.
<.> В качестве примера добавляется доступ к полю `MainInfo.Name` согласуемого документа.
====

=== Изменение разметки карточки вида "Согласование КС"

==== Разметка "Настройка"

Запрещается изменение и удаление существующих элементов управления разметки.

==== Разметка "Инициатор подготовка"

Запрещается удаление и замена элементов управления:

* Редактор этапов,
* Дерево версий,
* Вкладки дерева версий.

==== Разметка "Инициатор управление"

Запрещается изменение и удаление существующих элементов управления разметки.

=== Изменение разметки карточки вида "Этап согласования"

Запрещено изменять и удалять элементы управления в разметках карточки Этап согласования.

=== Изменение разметки карточки вида "Маршрут согласования"

Запрещено изменять и удалять элементы управления в разметках карточки Маршрут согласования.
