// tag::more-approvers[]
Добавление новых согласующих считается решением, имеющим семантику и не является отсутствием решения. Семантика решения может быть положительной или отрицательной в зависимости от настроек этапа.

Если решение влияет на повтора этапа. Например, при повторении этапа _Только для отказавших_ участник, добавивший новых согласующих, получает задание, только если в настройках этапа добавление согласующих является отрицательной семантикой. Если добавление согласующих является положительной семантикой (значение по умолчанию), новое задание не будет создано. В таком случае считается, что участник получил задание, и от него не поступало отказа.
// end::more-approvers[]

//tag::mode[]
.В зависимости от настроенного режима, версии будут отображаться по-разному:
* Процесс -- будут показаны все версии.
* Цикл -- будут показаны исходная версия текущего цикла и подчиненные.
* Этап -- будут показаны исходная версия текущего этапа и подчиненные.

[NOTE]
====
Новые файлы, xref:approval-add-files.adoc[добавленные] в согласование после его запуска, будут отображаться у согласующих после начала следующего этапа согласования.
====
//end::mode[]

//tag::on-finish[]
Если задание требует формирования электронной подписи, версия для подписания будет определена по следующей логике:

* В этапах с альтернативным и параллельным исполнением будет использована версия текущего согласующего.
** Если версия текущего согласующего отсутствует, будет использована версия этапа.
* В этапах с последовательным исполнением будет использована более поздняя версия любого согласующего.
** Если такая версия отсутствует, будет использована версия этапа.
//end::on-finish[]

//tag::in-sign-1[]
.В составе подписи могут быть:
* _Основные_ файлы.
//tag::in-sign-2[]
//tag::in-sign-3[]
* _Дополнительные_ файлы, если они присутствуют в карточке документа и в _Справочнике видов карточек_ настроено их включение в подпись.
//end::in-sign-3[]
* Набор полей, заданных в _Справочнике видов карточек_.
//tag::in-sign-3[]
* Метка подписи, если она была указана для решения в настройках этапа.
//end::in-sign-3[]
//end::in-sign-2[]
//end::in-sign-1[]

//tag::localized[]
Информация о ходе согласования (о замещении и делегировании, решения и т.д.) отображается в соответствии с настроенной локалью.
//end::localized[]
